# 01 — Raw Data Inventory & Schema Analysis

**Project:** Surgery Duration Prediction — Hillel Yaffe Medical Center  
**Stage:** Exploratory inventory (pre-ETL)  
**Constraint:** No merging, cleaning, imputation, or feature engineering.

This notebook performs a complete inventory of all raw datasets under `data/raw/` to understand structure, keys, relationships, and merge risks before building the ETL pipeline.

## 1. Setup & Configuration

In [50]:
import warnings
from pathlib import Path
from collections import defaultdict
from itertools import combinations

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 200)
pd.set_option("display.float_format", lambda x: f"{x:,.4f}")

RAW_DIR = Path("data/raw")
UNIQUENESS_PK_THRESHOLD = 0.95  # ratio of unique/total for PK candidacy
HIGH_UNIQUENESS_THRESHOLD = 0.90
CENTRAL_TABLE_CANDIDATE = "ניתוחים_260415"  # surgeries fact table

# Three parent departments in the mixed surgery dataset
PARENT_DEPARTMENTS = ["אף אוזן גרון", "אורטופדיה", "כירורגיה"]
SURGERY_DEPT_COLUMN = "מחלקה מנתחת"
DEPARTMENT_VALUE_COLUMNS = [
    "חדר", "קוד פרוצדורה", "שם פרוצדורה", "צד פרוצדורה",
    "קוד אבחנה", "שם אבחנה", "סוג ניתוח", "סוג הרדמה", "הרדמה פירוט",
    "מין", "סוג מקרה", "מנתח אחראי", " מרדים",
]

# Known column name aliases for cross-table join detection
CASE_ID_ALIASES = {"מספר מקרה", "מקרה"}
PATIENT_ID_ALIASES = {"patient", "Patient", "Medical Record"}

# Headerless lab CSV column names (file has no header row)
LAB_CSV_COLUMNS = [
    "Patient",
    "מספר מקרה",
    "קטגוריית בדיקה",
    "שם בדיקה",
    "ערך",
    "תאריך בדיקה",
]

# Human-readable dataset descriptions (inferred from filenames)
DATASET_DESCRIPTIONS = {
    "ניתוחים_260415": "Surgery cases — procedures, timestamps, staff, anesthesia (likely central fact table)",
    "בדיקות מעבדה": "Pre-operative laboratory test results (long format, multiple tests per case)",
    "הרדמה": "Anesthesia type per surgery case",
    "זמן חתימת מנתח על sign in": "Surgeon electronic sign-in timestamp per case",
    "זמן חתימת מנתח על sign out": "Surgeon electronic sign-out timestamp per case",
    "לחץ דם": "Pre-operative blood pressure (systolic/diastolic) per case",
    "מחלות רקע": "Patient background diseases (ICD-9 codes, patient-level)",
    "סוג דם גובה משקל BMI": "Patient vitals: blood type, height, weight, BMI per case",
    "סטורציה": "Pre-operative oxygen saturation per case",
    "עישון": "Smoking status per surgery case",
    "צוות סיעודי בניתוח": "Scrub nurse assignments per case (may be multi-valued)",
    "רגישות אחרת": "Other allergies/sensitivities (patient-level)",
    "רגישות לתרופות": "Drug allergies/sensitivities (patient-level)",
    "תרופות בניתוח": "Medications administered during surgery (long format)",
    "תרופות קבועות": "Chronic/home medications (patient-level)",
}

print(f"Raw data directory: {RAW_DIR.resolve()}")
print(f"Files found: {len(list(RAW_DIR.iterdir()))}")

Raw data directory: /home/gur/Documents/Ruppin/CSY3/Final Project/סמסטר ב/ml_data_pipeline/data/raw
Files found: 15

## 2. Helper Functions

Reusable analysis utilities for per-dataset and cross-table inventory.

In [51]:
def load_raw_dataset(file_path: Path) -> pd.DataFrame:
    """Load a single raw file with format-specific handling."""
    stem = file_path.stem
    if file_path.suffix.lower() == ".csv":
        df = pd.read_csv(
            file_path,
            header=None,
            names=LAB_CSV_COLUMNS,
            encoding="utf-8-sig",
            low_memory=False,
        )
    else:
        df = pd.read_excel(file_path)
    df.attrs["source_file"] = file_path.name
    df.attrs["dataset_name"] = stem
    return df


def normalize_col_name(col: str) -> str:
    return str(col).strip().lower()


def schema_summary(df: pd.DataFrame) -> pd.DataFrame:
    """Detailed column-level schema summary."""
    rows = []
    n = len(df)
    for col in df.columns:
        s = df[col]
        null_count = int(s.isna().sum())
        non_null = n - null_count
        nunique = int(s.nunique(dropna=True))
        rows.append({
            "column": col,
            "dtype": str(s.dtype),
            "non_null_count": non_null,
            "null_count": null_count,
            "null_pct": round(100 * null_count / n, 2) if n else 0,
            "n_unique": nunique,
            "uniqueness_ratio": round(nunique / non_null, 4) if non_null else np.nan,
        })
    return pd.DataFrame(rows).sort_values("column").reset_index(drop=True)


def is_likely_date_column(col: str) -> bool:
    """Heuristic: exclude timestamp columns from PK candidacy."""
    date_keywords = ["תאריך", "מועד", "date", "time", "sign in", "sign out", "entry_date", "זמן", "שעת"]
    col_str = str(col).lower()
    return any(kw in col_str or kw in str(col) for kw in date_keywords)


def detect_id_columns(df: pd.DataFrame, schema: pd.DataFrame) -> pd.DataFrame:
    """Identify potential identifier / primary-key columns."""
    records = []
    for _, row in schema.iterrows():
        col = row["column"]
        norm = normalize_col_name(col)
        is_date_col = is_likely_date_column(col)
        name_match = (
            norm.endswith("_id")
            or norm.endswith(" id")
            or col in CASE_ID_ALIASES
            or col in PATIENT_ID_ALIASES
        )
        reasons = []
        if name_match:
            reasons.append("name_pattern")
        if row["uniqueness_ratio"] >= HIGH_UNIQUENESS_THRESHOLD and not is_date_col:
            reasons.append("high_uniqueness")
        if row["uniqueness_ratio"] == 1.0 and row["null_count"] == 0 and not is_date_col:
            reasons.append("unique_no_nulls")
        if reasons:
            pk_candidate = (
                name_match
                and row["null_count"] == 0
                and row["uniqueness_ratio"] >= UNIQUENESS_PK_THRESHOLD
            )
            records.append({
                "column": col,
                "n_unique": row["n_unique"],
                "uniqueness_ratio": row["uniqueness_ratio"],
                "null_count": row["null_count"],
                "reasons": ", ".join(reasons),
                "pk_candidate": pk_candidate,
            })
    return pd.DataFrame(records).sort_values(["pk_candidate", "uniqueness_ratio"], ascending=[False, False]).reset_index(drop=True)


def check_data_quality(df: pd.DataFrame, id_cols: pd.DataFrame) -> dict:
    """Duplicate row and PK-candidate duplicate checks."""
    dup_rows = int(df.duplicated().sum())
    pk_dup_details = []
    if not id_cols.empty:
        for col in id_cols.loc[id_cols["pk_candidate"], "column"]:
            dup_vals = int(df[col].duplicated().sum() - df[col].isna().sum())
            dup_count = int(df[col].duplicated(keep=False).sum())
            pk_dup_details.append({"column": col, "rows_in_duplicate_groups": dup_count, "is_unique": dup_count == 0})
    return {"duplicate_rows": dup_rows, "pk_duplicate_checks": pd.DataFrame(pk_dup_details)}


def identify_date_columns(df: pd.DataFrame) -> list:
    """Auto-detect date/datetime columns by name and parseability."""
    date_keywords = ["תאריך", "מועד", "date", "time", "sign in", "sign out", "entry_date", "זמן", "שעת"]
    candidates = []
    for col in df.columns:
        col_lower = str(col).lower()
        if any(kw in col_lower or kw in str(col) for kw in date_keywords):
            candidates.append(col)
            continue
        if pd.api.types.is_datetime64_any_dtype(df[col]):
            candidates.append(col)
            continue
        if df[col].dtype == object:
            sample = df[col].dropna().head(200)
            if len(sample) == 0:
                continue
            parsed = pd.to_datetime(sample, errors="coerce", dayfirst=True)
            if parsed.notna().mean() >= 0.8:
                candidates.append(col)
    return list(dict.fromkeys(candidates))


def analyze_date_columns(df: pd.DataFrame, date_cols: list) -> pd.DataFrame:
    if not date_cols:
        return pd.DataFrame()
    rows = []
    for col in date_cols:
        s = pd.to_datetime(df[col], errors="coerce", dayfirst=True)
        valid = s.dropna()
        rows.append({
            "column": col,
            "min_date": valid.min(),
            "max_date": valid.max(),
            "n_unique_dates": int(valid.dt.normalize().nunique()) if len(valid) else 0,
            "null_count": int(s.isna().sum()),
            "parseable_pct": round(100 * valid.shape[0] / len(df), 2),
        })
    return pd.DataFrame(rows)


def build_date_range_summary(datasets: dict) -> pd.DataFrame:
    """Per-dataset date column coverage: first/last observed dates and year span."""
    rows = []
    for name, info in datasets.items():
        date_analysis = info.get("date_analysis", pd.DataFrame())
        if date_analysis.empty:
            rows.append({
                "dataset": name,
                "date_column": "—",
                "first_date": pd.NaT,
                "last_date": pd.NaT,
                "year_span": np.nan,
                "n_unique_dates": 0,
            })
            continue
        for _, row in date_analysis.iterrows():
            first = row["min_date"]
            last = row["max_date"]
            year_span = (last.year - first.year + 1) if pd.notna(first) and pd.notna(last) else np.nan
            rows.append({
                "dataset": name,
                "date_column": row["column"],
                "first_date": first,
                "last_date": last,
                "year_span": year_span,
                "n_unique_dates": row["n_unique_dates"],
            })
    return pd.DataFrame(rows)


def map_parent_department(dept_value) -> str | None:
    """Map sub-unit (e.g. 'אורטופדיה א') to one of three parent departments."""
    if pd.isna(dept_value):
        return None
    s = str(dept_value).strip()
    if any(k in s for k in ("אף", "אוזן", "גרון")):
        return "אף אוזן גרון"
    if "אורטופדיה" in s:
        return "אורטופדיה"
    if "כירורגיה" in s:
        return "כירורגיה"
    return "אחר"


def department_volume_summary(df: pd.DataFrame, dept_col: str = SURGERY_DEPT_COLUMN) -> pd.DataFrame:
    """Row/case/patient counts per surgical sub-unit and parent department."""
    if dept_col not in df.columns:
        return pd.DataFrame()
    rows = []
    for subunit, grp in df.groupby(dept_col, dropna=False):
        row = {
            "מחלקה מנתחת": subunit,
            "מחלקה ראשית": map_parent_department(subunit),
            "n_rows": len(grp),
        }
        if "מספר מקרה" in df.columns:
            row["n_unique_cases"] = int(grp["מספר מקרה"].nunique())
        if "patient" in df.columns:
            row["n_unique_patients"] = int(grp["patient"].nunique())
        rows.append(row)
    return (
        pd.DataFrame(rows)
        .sort_values(["מחלקה ראשית", "מחלקה מנתחת"])
        .reset_index(drop=True)
    )


def unique_values_by_department(
    df: pd.DataFrame,
    columns: list | None = None,
    dept_col: str = SURGERY_DEPT_COLUMN,
) -> pd.DataFrame:
    """Distinct non-null value counts per column, pivoted by parent department."""
    if dept_col not in df.columns:
        return pd.DataFrame()
    value_cols = [c for c in (columns or DEPARTMENT_VALUE_COLUMNS) if c in df.columns]
    if not value_cols:
        return pd.DataFrame()

    tmp = df.copy()
    tmp["מחלקה ראשית"] = tmp[dept_col].map(map_parent_department)
    tmp = tmp[tmp["מחלקה ראשית"].isin(PARENT_DEPARTMENTS)]

    rows = []
    for col in value_cols:
        for dept in PARENT_DEPARTMENTS:
            sub = tmp.loc[tmp["מחלקה ראשית"] == dept, col]
            rows.append({
                "column": col,
                "מחלקה ראשית": dept,
                "n_unique_values": int(sub.nunique(dropna=True)),
                "n_non_null": int(sub.notna().sum()),
            })
    long_df = pd.DataFrame(rows)
    pivot = long_df.pivot(index="column", columns="מחלקה ראשית", values="n_unique_values")
    return pivot[PARENT_DEPARTMENTS].reset_index()


def analyze_numeric_columns(df: pd.DataFrame) -> pd.DataFrame:
    num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    if not num_cols:
        return pd.DataFrame()
    desc = df[num_cols].describe().T
    desc = desc.rename(columns={"50%": "median"})
    desc["column"] = desc.index
    return desc[["column", "count", "mean", "std", "min", "median", "max"]].reset_index(drop=True)


def analyze_categorical_columns(df: pd.DataFrame, max_cardinality: int = 500) -> dict:
    """Top-20 value counts for low/medium cardinality object columns."""
    results = {}
    for col in df.select_dtypes(include=["object", "string"]).columns:
        nunique = df[col].nunique(dropna=True)
        if nunique > max_cardinality:
            results[col] = {
                "n_unique": nunique,
                "note": f"High cardinality ({nunique} categories) — showing top 20 only",
                "top_20": df[col].value_counts(dropna=False).head(20),
            }
        else:
            results[col] = {
                "n_unique": nunique,
                "note": None,
                "top_20": df[col].value_counts(dropna=False).head(20),
            }
    return results


def get_standardized_key_columns(df: pd.DataFrame) -> dict:
    """Map dataset columns to semantic roles for cross-table analysis."""
    mapping = {"case_id": None, "patient_id": None, "medical_record": None}
    for col in df.columns:
        norm = normalize_col_name(col)
        if col in CASE_ID_ALIASES or norm in {normalize_col_name(x) for x in CASE_ID_ALIASES}:
            mapping["case_id"] = col
        if col in PATIENT_ID_ALIASES or norm in {normalize_col_name(x) for x in PATIENT_ID_ALIASES}:
            if norm == "medical record":
                mapping["medical_record"] = col
            else:
                mapping["patient_id"] = col
    return mapping


def classify_relationship(n_a: int, u_a: int, n_b: int, u_b: int, overlap: int) -> str:
    """Classify join relationship based on uniqueness and overlap."""
    if overlap == 0:
        return "No overlap"
    left_unique = u_a == n_a
    right_unique = u_b == n_b
    if left_unique and right_unique:
        return "One-to-One (1:1)"
    if left_unique and not right_unique:
        return "One-to-Many (1:N)"
    if not left_unique and right_unique:
        return "Many-to-One (N:1)"
    return "Many-to-Many (N:N)"


def analyze_dataset(file_path: Path) -> dict:
    """Full per-dataset inventory analysis."""
    df = load_raw_dataset(file_path)
    name = file_path.stem
    schema = schema_summary(df)
    id_cols = detect_id_columns(df, schema)
    quality = check_data_quality(df, id_cols)
    date_cols = identify_date_columns(df)
    date_analysis = analyze_date_columns(df, date_cols)
    numeric_analysis = analyze_numeric_columns(df)
    cat_analysis = analyze_categorical_columns(df)
    keys = get_standardized_key_columns(df)

    pk_candidates = id_cols.loc[id_cols["pk_candidate"], "column"].tolist() if not id_cols.empty else []

    return {
        "name": name,
        "file": file_path.name,
        "description": DATASET_DESCRIPTIONS.get(name, "—"),
        "df": df,
        "n_rows": len(df),
        "n_cols": len(df.columns),
        "memory_mb": round(df.memory_usage(deep=True).sum() / 1e6, 2),
        "schema": schema,
        "id_columns": id_cols,
        "pk_candidates": pk_candidates,
        "quality": quality,
        "date_cols": date_cols,
        "date_analysis": date_analysis,
        "numeric_analysis": numeric_analysis,
        "categorical_analysis": cat_analysis,
        "keys": keys,
    }

## 3. Load All Raw Datasets

In [52]:
raw_files = sorted(
    [p for p in RAW_DIR.iterdir() if p.suffix.lower() in {".csv", ".xlsx", ".xls"}],
    key=lambda p: p.name,
)

print("Files to analyze:")
for f in raw_files:
    print(f"  • {f.name}")

datasets = {}
load_errors = {}

for f in raw_files:
    try:
        print(f"Loading {f.name}...", end=" ")
        datasets[f.stem] = analyze_dataset(f)
        print(f"OK — {datasets[f.stem]['n_rows']:,} rows × {datasets[f.stem]['n_cols']} cols")
    except Exception as e:
        load_errors[f.name] = str(e)
        print(f"FAILED — {e}")

if load_errors:
    print("\n⚠️ Load errors:")
    for k, v in load_errors.items():
        print(f"  {k}: {v}")
else:
    print(f"\n✓ Successfully loaded {len(datasets)} datasets")

Files to analyze:
  • בדיקות מעבדה.csv
  • הרדמה.xlsx
  • זמן חתימת מנתח על sign in.xlsx
  • זמן חתימת מנתח על sign out.xlsx
  • לחץ דם.xlsx
  • מחלות רקע.xlsx
  • ניתוחים_260415.xlsx
  • סוג דם גובה משקל BMI.xlsx
  • סטורציה.xlsx
  • עישון.xlsx
  • צוות סיעודי בניתוח.xlsx
  • רגישות אחרת.xlsx
  • רגישות לתרופות.xlsx
  • תרופות בניתוח.xlsx
  • תרופות קבועות.xlsx
Loading בדיקות מעבדה.csv... OK — 3,715,761 rows × 6 cols
Loading הרדמה.xlsx... OK — 33,027 rows × 3 cols
Loading זמן חתימת מנתח על sign in.xlsx... OK — 28,987 rows × 3 cols
Loading זמן חתימת מנתח על sign out.xlsx... OK — 27,709 rows × 3 cols
Loading לחץ דם.xlsx... OK — 35,678 rows × 5 cols
Loading מחלות רקע.xlsx... OK — 35,359 rows × 3 cols
Loading ניתוחים_260415.xlsx... OK — 46,909 rows × 44 cols
Loading סוג דם גובה משקל BMI.xlsx... OK — 34,521 rows × 7 cols
Loading סטורציה.xlsx... OK — 27,625 rows × 4 cols
Loading עישון.xlsx... OK — 31,661 rows × 4 cols
Loading צוות סיעודי בניתוח.xlsx... OK — 32,831 rows × 3 cols
Loading רגישות אחרת.xlsx... OK — 1,782 rows × 4 cols
Loading רגישות לתרופות.xlsx... OK — 8,820 rows × 3 cols
Loading תרופות בניתוח.xlsx... OK — 319,950 rows × 4 cols
Loading תרופות קבועות.xlsx... OK — 7,319 rows × 3 cols

✓ Successfully loaded 15 datasets

## 4. Dataset-by-Dataset Analysis

For each raw file: schema, identifiers, data quality, dates, numerics, and categoricals.

In [53]:
for name, info in datasets.items():
    display(pd.DataFrame([{
        "Dataset": name,
        "File": info["file"],
        "Description": info["description"],
        "Rows": f"{info['n_rows']:,}",
        "Columns": info["n_cols"],
        "Memory (MB)": info["memory_mb"],
        "PK Candidates": ", ".join(info["pk_candidates"]) or "—",
        "Case ID Col": info["keys"]["case_id"] or "—",
        "Patient ID Col": info["keys"]["patient_id"] or "—",
    }]))

        Dataset              File                                        Description       Rows  Columns  Memory (MB) PK Candidates Case ID Col Patient ID Col
0  בדיקות מעבדה  בדיקות מעבדה.csv  Pre-operative laboratory test results (long fo...  3,715,761        6   1,415.5800             —   מספר מקרה        Patient

  Dataset        File                       Description    Rows  Columns  Memory (MB) PK Candidates Case ID Col Patient ID Col
0   הרדמה  הרדמה.xlsx  Anesthesia type per surgery case  33,027        3       2.6600             —   מספר מקרה        Patient

                     Dataset                            File                                    Description    Rows  Columns  Memory (MB) PK Candidates Case ID Col Patient ID Col
0  זמן חתימת מנתח על sign in  זמן חתימת מנתח על sign in.xlsx  Surgeon electronic sign-in timestamp per case  28,987        3       0.7000     מספר מקרה   מספר מקרה        Patient

                      Dataset                             File                                     Description    Rows  Columns  Memory (MB) PK Candidates Case ID Col Patient ID Col
0  זמן חתימת מנתח על sign out  זמן חתימת מנתח על sign out.xlsx  Surgeon electronic sign-out timestamp per case  27,709        3       0.6700     מספר מקרה   מספר מקרה        Patient

  Dataset         File                                        Description    Rows  Columns  Memory (MB) PK Candidates Case ID Col Patient ID Col
0  לחץ דם  לחץ דם.xlsx  Pre-operative blood pressure (systolic/diastol...  35,678        5       1.4300             —        מקרה        Patient

     Dataset            File                                        Description    Rows  Columns  Memory (MB) PK Candidates Case ID Col Patient ID Col
0  מחלות רקע  מחלות רקע.xlsx  Patient background diseases (ICD-9 codes, pati...  35,359        3       4.8100             —           —        Patient

          Dataset                 File                                        Description    Rows  Columns  Memory (MB) PK Candidates Case ID Col Patient ID Col
0  ניתוחים_260415  ניתוחים_260415.xlsx  Surgery cases — procedures, timestamps, staff,...  46,909       44     107.9400             —   מספר מקרה        patient

                Dataset                       File                                        Description    Rows  Columns  Memory (MB) PK Candidates Case ID Col Patient ID Col
0  סוג דם גובה משקל BMI  סוג דם גובה משקל BMI.xlsx  Patient vitals: blood type, height, weight, BM...  34,521        7       3.2200             —   מספר מקרה        Patient

   Dataset          File                               Description    Rows  Columns  Memory (MB) PK Candidates Case ID Col Patient ID Col
0  סטורציה  סטורציה.xlsx  Pre-operative oxygen saturation per case  27,625        4       0.8800          מקרה        מקרה        Patient

  Dataset        File                      Description    Rows  Columns  Memory (MB) PK Candidates Case ID Col Patient ID Col
0   עישון  עישון.xlsx  Smoking status per surgery case  31,661        4       1.0100             —   מספר מקרה        Patient

              Dataset                     File                                        Description    Rows  Columns  Memory (MB) PK Candidates Case ID Col Patient ID Col
0  צוות סיעודי בניתוח  צוות סיעודי בניתוח.xlsx  Scrub nurse assignments per case (may be multi...  32,831        3       4.8600             —   מספר מקרה        Patient

       Dataset              File                                    Description   Rows  Columns  Memory (MB) PK Candidates Case ID Col Patient ID Col
0  רגישות אחרת  רגישות אחרת.xlsx  Other allergies/sensitivities (patient-level)  1,782        4       0.3000             —           —        Patient

          Dataset                 File                                   Description   Rows  Columns  Memory (MB) PK Candidates Case ID Col Patient ID Col
0  רגישות לתרופות  רגישות לתרופות.xlsx  Drug allergies/sensitivities (patient-level)  8,820        3       0.7800             —           —        Patient

         Dataset                File                                        Description     Rows  Columns  Memory (MB) PK Candidates Case ID Col Patient ID Col
0  תרופות בניתוח  תרופות בניתוח.xlsx  Medications administered during surgery (long ...  319,950        4      51.2900             —   מספר מקרה        Patient

         Dataset                File                               Description   Rows  Columns  Memory (MB) PK Candidates Case ID Col Patient ID Col
0  תרופות קבועות  תרופות קבועות.xlsx  Chronic/home medications (patient-level)  7,319        3       0.6800             —           —        Patient

In [54]:
for name, info in datasets.items():
    print("=" * 90)
    print(f"DATASET: {name}")
    print(f"File: {info['file']}  |  Rows: {info['n_rows']:,}  |  Cols: {info['n_cols']}  |  Memory: {info['memory_mb']} MB")
    print(f"Description: {info['description']}")
    print("=" * 90)

    print("\n--- Schema Summary ---")
    display(info["schema"])

    print("\n--- Potential Identifier Columns ---")
    if info["id_columns"].empty:
        print("No strong identifier columns detected.")
    else:
        display(info["id_columns"])

    print("\n--- Data Quality ---")
    print(f"Duplicate rows (full row): {info['quality']['duplicate_rows']:,}")
    pk_dup = info["quality"]["pk_duplicate_checks"]
    if not pk_dup.empty:
        display(pk_dup)
    else:
        print("No PK-candidate columns to check for duplicates.")

    print("\n--- Date Column Analysis ---")
    if info["date_analysis"].empty:
        print("No date columns detected.")
    else:
        display(info["date_analysis"])

    print("\n--- Numeric Column Statistics ---")
    if info["numeric_analysis"].empty:
        print("No numeric columns.")
    else:
        display(info["numeric_analysis"])

    print("\n--- Categorical Column Analysis (Top 20) ---")
    if not info["categorical_analysis"]:
        print("No categorical (object) columns.")
    else:
        for col, cat_info in info["categorical_analysis"].items():
            print(f"\n  Column: {col}  |  Unique categories: {cat_info['n_unique']:,}")
            if cat_info["note"]:
                print(f"  Note: {cat_info['note']}")
            display(cat_info["top_20"].to_frame("count"))

    print("\n--- Sample Rows (first 3) ---")
    display(info["df"].head(3))

    print("\n")

==========================================================================================
DATASET: בדיקות מעבדה
File: בדיקות מעבדה.csv  |  Rows: 3,715,761  |  Cols: 6  |  Memory: 1415.58 MB
Description: Pre-operative laboratory test results (long format, multiple tests per case)
==========================================================================================

--- Schema Summary ---

           column   dtype  non_null_count  null_count  null_pct  n_unique  uniqueness_ratio
0         Patient   int64         3715761           0    0.0000     16520            0.0044
1       מספר מקרה   int64         3715761           0    0.0000     19400            0.0052
2             ערך  object         3711920        3841    0.1000     15504            0.0042
3  קטגוריית בדיקה  object         3715761           0    0.0000         4            0.0000
4        שם בדיקה  object         3715761           0    0.0000        87            0.0000
5     תאריך בדיקה  object         3715761           0    0.0000    165489            0.0445

--- Potential Identifier Columns ---

      column  n_unique  uniqueness_ratio  null_count       reasons  pk_candidate
0  מספר מקרה     19400            0.0052           0  name_pattern         False
1    Patient     16520            0.0044           0  name_pattern         False

--- Data Quality ---
Duplicate rows (full row): 0
No PK-candidate columns to check for duplicates.

--- Date Column Analysis ---

        column            min_date            max_date  n_unique_dates  null_count  parseable_pct
0  תאריך בדיקה 2019-01-04 08:55:00 2026-12-02 18:32:00            1002     2228188        40.0300

--- Numeric Column Statistics ---

      column          count            mean            std        min          median             max
0    Patient 3,715,761.0000    221,619.8694   178,771.0165   220.0000    176,769.0000    794,477.0000
1  מספר מקרה 3,715,761.0000 12,175,384.1859 3,538,089.5111 4,093.0000 11,595,721.0000 32,474,177.0000

--- Categorical Column Analysis (Top 20) ---

  Column: קטגוריית בדיקה  |  Unique categories: 4

                        count
קטגוריית בדיקה
המטולוגיה- ספירת דם   1973712
ביוכימיה - כימיה בדם  1598281
המטולוגיה- קרישה       100525
ביוכימיה - סמני לב      43243

  Column: שם בדיקה  |  Unique categories: 87

                                   count
שם בדיקה
Lipemic Index-B                    88563
Hemolysis Index -B                 88558
Icteric Index-B                    88358
Sodium-B                           85108
BUN-B                              84317
Creatinine-B                       84004
Glucose-B                          83246
HGB                                83048
Platelet, automated count - blood  82819
HCT                                82505
WBC                                82347
NEUTRO abs                         82226
RBC                                82226
LYMPHO%                            82226
MONO abs                           82225
LYMPHO abs                         82225
MPV                                82225
MONO%                              82225
NEUTRO%                            82224
MCV                                82223

  Column: ערך  |  Unique categories: 15,504
  Note: High cardinality (15504 categories) — showing top 20 only

         count
ערך
NORMAL  232574
0.2      67467
0.1      50659
0.3      42231
0.0      29048
0.04     21630
0.4      20918
+        19166
0.05     17022
0.5      16437
0.02     16146
0.06     15413
0.6      13684
0.03     13216
0.01     13054
0.07     12133
0.7      11511
0.8      10711
3.0      10292
++        9821

  Column: תאריך בדיקה  |  Unique categories: 165,489
  Note: High cardinality (165489 categories) — showing top 20 only

                         count
תאריך בדיקה
2023-06-04 07:59:00.000    531
2023-09-07 08:22:00.000    531
2022-10-31 08:25:00.000    480
2023-08-14 08:20:00.000    480
2023-03-11 15:50:00.000    460
2022-12-19 07:54:00.000    457
2023-01-25 08:01:00.000    456
2024-11-05 08:24:00.000    456
2023-12-05 08:09:00.000    456
2023-08-24 08:25:00.000    456
2023-05-14 07:46:00.000    456
2023-04-25 08:00:00.000    432
2024-04-04 08:39:00.000    408
2023-03-01 08:08:00.000    408
2022-12-07 08:06:00.000    408
2023-08-27 08:06:00.000    408
2023-04-10 07:58:00.000    408
2021-02-25 08:06:00.000    406
2022-11-28 09:01:00.000    399
2023-08-30 08:02:00.000    384

--- Sample Rows (first 3) ---

   Patient  מספר מקרה        קטגוריית בדיקה      שם בדיקה   ערך              תאריך בדיקה
0   100020   11529175  ביוכימיה - כימיה בדם    Chloride-B   106  2022-10-02 03:06:00.000
1   100020   11529175  ביוכימיה - כימיה בדם         BUN-B  10.6  2022-10-02 03:19:00.000
2   100020   11529175  ביוכימיה - כימיה בדם  Creatinine-B  1.34  2022-10-02 03:19:00.000

==========================================================================================
DATASET: הרדמה
File: הרדמה.xlsx  |  Rows: 33,027  |  Cols: 3  |  Memory: 2.66 MB
Description: Anesthesia type per surgery case
==========================================================================================

--- Schema Summary ---

      column    dtype  non_null_count  null_count  null_pct  n_unique  uniqueness_ratio
0    Patient    int64           33027           0    0.0000     27845            0.8431
1      הרדמה   object           33027           0    0.0000        11            0.0003
2  מספר מקרה  float64           33026           1    0.0000     32681            0.9896

--- Potential Identifier Columns ---

      column  n_unique  uniqueness_ratio  null_count                        reasons  pk_candidate
0  מספר מקרה     32681            0.9896           1  name_pattern, high_uniqueness         False
1    Patient     27845            0.8431           0                   name_pattern         False

--- Data Quality ---
Duplicate rows (full row): 0
No PK-candidate columns to check for duplicates.

--- Date Column Analysis ---
No date columns detected.

--- Numeric Column Statistics ---

      column       count            mean            std        min          median             max
0    Patient 33,027.0000    281,093.7339   190,842.3650   220.0000    263,702.0000    789,385.0000
1  מספר מקרה 33,026.0000 13,535,187.6975 6,041,784.9976 4,093.0000 11,625,623.0000 32,451,338.0000

--- Categorical Column Analysis (Top 20) ---

  Column: הרדמה  |  Unique categories: 11

                    count
הרדמה
General             26028
Sedation             2085
Local                1602
General + Local       853
General + Regional    776
Spinal                749
Other                 526
Regional              266
Spinal + Epidural      90
Local + Regional       30
Epidural               22

--- Sample Rows (first 3) ---

   Patient       מספר מקרה    הרדמה
0   100020 11,529,175.0000  General
1   100021 11,604,766.0000  General
2   100033 31,691,869.0000    Local

==========================================================================================
DATASET: זמן חתימת מנתח על sign in
File: זמן חתימת מנתח על sign in.xlsx  |  Rows: 28,987  |  Cols: 3  |  Memory: 0.7 MB
Description: Surgeon electronic sign-in timestamp per case
==========================================================================================

--- Schema Summary ---

        column           dtype  non_null_count  null_count  null_pct  n_unique  uniqueness_ratio
0      Patient           int64           28987           0    0.0000     23837            0.8223
1  זמן sign in  datetime64[ns]           28987           0    0.0000     28987            1.0000
2    מספר מקרה           int64           28987           0    0.0000     27677            0.9548

--- Potential Identifier Columns ---

      column  n_unique  uniqueness_ratio  null_count                        reasons  pk_candidate
0  מספר מקרה     27677            0.9548           0  name_pattern, high_uniqueness          True
1    Patient     23837            0.8223           0                   name_pattern         False

--- Data Quality ---
Duplicate rows (full row): 0

      column  rows_in_duplicate_groups  is_unique
0  מספר מקרה                      2283      False

--- Date Column Analysis ---

        column                min_date                max_date  n_unique_dates  null_count  parseable_pct
0  זמן sign in 2021-01-21 10:45:39.280 2026-02-18 11:40:39.730            1819           0       100.0000

--- Numeric Column Statistics ---

      column       count            mean            std        min          median             max
0    Patient 28,987.0000    300,224.7940   201,903.3338   220.0000    277,538.0000    794,504.0000
1  מספר מקרה 28,987.0000 13,530,272.1492 5,913,536.2918 4,093.0000 11,693,606.0000 32,474,177.0000

--- Categorical Column Analysis (Top 20) ---
No categorical (object) columns.

--- Sample Rows (first 3) ---

   Patient  מספר מקרה             זמן sign in
0   100020   11529175 2022-12-12 14:02:58.867
1   100021   11604766 2023-04-10 08:22:36.330
2   100033   31691869 2022-03-29 13:15:09.693

==========================================================================================
DATASET: זמן חתימת מנתח על sign out
File: זמן חתימת מנתח על sign out.xlsx  |  Rows: 27,709  |  Cols: 3  |  Memory: 0.67 MB
Description: Surgeon electronic sign-out timestamp per case
==========================================================================================

--- Schema Summary ---

         column           dtype  non_null_count  null_count  null_pct  n_unique  uniqueness_ratio
0       Patient           int64           27709           0    0.0000     22959            0.8286
1  זמן sign out  datetime64[ns]           27709           0    0.0000     27709            1.0000
2     מספר מקרה           int64           27709           0    0.0000     26494            0.9562

--- Potential Identifier Columns ---

      column  n_unique  uniqueness_ratio  null_count                        reasons  pk_candidate
0  מספר מקרה     26494            0.9562           0  name_pattern, high_uniqueness          True
1    Patient     22959            0.8286           0                   name_pattern         False

--- Data Quality ---
Duplicate rows (full row): 0

      column  rows_in_duplicate_groups  is_unique
0  מספר מקרה                      2102      False

--- Date Column Analysis ---

         column                min_date                max_date  n_unique_dates  null_count  parseable_pct
0  זמן sign out 2021-01-21 10:24:34.850 2026-02-18 13:57:14.137            1819           0       100.0000

--- Numeric Column Statistics ---

      column       count            mean            std        min          median             max
0    Patient 27,709.0000    300,116.7665   201,400.0181   220.0000    278,117.0000    794,504.0000
1  מספר מקרה 27,709.0000 13,477,215.5093 5,842,321.9781 4,093.0000 11,690,216.0000 32,474,177.0000

--- Categorical Column Analysis (Top 20) ---
No categorical (object) columns.

--- Sample Rows (first 3) ---

   Patient  מספר מקרה            זמן sign out
0   100020   11529175 2022-12-12 15:18:39.490
1   100021   11604766 2023-04-10 12:47:38.627
2   100033   31691869 2022-03-29 13:54:58.463

==========================================================================================
DATASET: לחץ דם
File: לחץ דם.xlsx  |  Rows: 35,678  |  Cols: 5  |  Memory: 1.43 MB
Description: Pre-operative blood pressure (systolic/diastolic) per case
==========================================================================================

--- Schema Summary ---

                column           dtype  non_null_count  null_count  null_pct  n_unique  uniqueness_ratio
0              Patient           int64           35678           0    0.0000     27013            0.7571
1  דיאסטולי לפני ניתוח         float64           35646          32    0.0900        99            0.0028
2   היסטולי לפני ניתוח         float64           35646          32    0.0900       161            0.0045
3                 מקרה         float64           35677           1    0.0000     31816            0.8918
4          תאריך ניתוח  datetime64[ns]           35678           0    0.0000      2184            0.0612

--- Potential Identifier Columns ---

    column  n_unique  uniqueness_ratio  null_count       reasons  pk_candidate
0     מקרה     31816            0.8918           1  name_pattern         False
1  Patient     27013            0.7571           0  name_pattern         False

--- Data Quality ---
Duplicate rows (full row): 2,864
No PK-candidate columns to check for duplicates.

--- Date Column Analysis ---

        column   min_date   max_date  n_unique_dates  null_count  parseable_pct
0  תאריך ניתוח 2020-01-20 2026-02-18            2184           0       100.0000

--- Numeric Column Statistics ---

                column       count            mean            std        min          median             max
0              Patient 35,678.0000    279,850.2924   193,510.1457   220.0000    260,763.5000    794,504.0000
1                 מקרה 35,677.0000 13,048,565.5187 5,318,142.9014 4,093.0000 11,622,493.0000 32,474,177.0000
2   היסטולי לפני ניתוח 35,646.0000        127.6117        20.1825    32.0000        125.0000        232.0000
3  דיאסטולי לפני ניתוח 35,646.0000         72.6808        12.2290    22.0000         73.0000        874.0000

--- Categorical Column Analysis (Top 20) ---
No categorical (object) columns.

--- Sample Rows (first 3) ---

   Patient            מקרה תאריך ניתוח  היסטולי לפני ניתוח  דיאסטולי לפני ניתוח
0    51923 11,028,836.0000  2020-01-21            116.0000              62.0000
1   266039 11,033,725.0000  2020-01-21             90.0000              50.0000
2   264745 11,035,095.0000  2020-01-20            140.0000              70.0000

==========================================================================================
DATASET: מחלות רקע
File: מחלות רקע.xlsx  |  Rows: 35,359  |  Cols: 3  |  Memory: 4.81 MB
Description: Patient background diseases (ICD-9 codes, patient-level)
==========================================================================================

--- Schema Summary ---

    column   dtype  non_null_count  null_count  null_pct  n_unique  uniqueness_ratio
0     ICD9  object           35359           0    0.0000      2899            0.0820
1     Name  object           35359           0    0.0000      3767            0.1065
2  Patient   int64           35359           0    0.0000     10781            0.3049

--- Potential Identifier Columns ---

    column  n_unique  uniqueness_ratio  null_count       reasons  pk_candidate
0  Patient     10781            0.3049           0  name_pattern         False

--- Data Quality ---
Duplicate rows (full row): 0
No PK-candidate columns to check for duplicates.

--- Date Column Analysis ---

  column   min_date   max_date  n_unique_dates  null_count  parseable_pct
0   ICD9 1970-01-01 2054-07-21              39        3014        91.4800

--- Numeric Column Statistics ---

    column       count         mean          std      min       median          max
0  Patient 35,359.0000 200,948.5869 162,718.5958 220.0000 161,795.0000 792,910.0000

--- Categorical Column Analysis (Top 20) ---

  Column: ICD9  |  Unique categories: 2,899
  Note: High cardinality (2899 categories) — showing top 20 only

        count
ICD9
272.4    2922
401.9    2582
401.1    2043
250      1698
414.9     961
305.1     801
250.02    678
278       670
427.31    667
244.9     622
493.9     502
250.9     495
278.01    483
496       387
285.9     373
600       300
733       282
V15.82    257
272.2     249
585.9     227

  Column: Name  |  Unique categories: 3,767
  Note: High cardinality (3767 categories) — showing top 20 only

                                                    count
Name
UNSPECIFIED ESSENTIAL HYPERTENSION                   1737
OTHER AND UNSPECIFIED HYPERLIPIDEMIA                 1211
HYPERLIPIDEMIA                                       1133
BENIGN ESSENTIAL HYPERTENSION                        1020
TOBACCO USE DISORDER                                  605
DIABETES MELLITUS WITHOUT MENTION OF COMPLICATI...    582
ATRIAL FIBRILLATION                                   577
DIABETES MELLITUS                                     572
Essential Hypertension                                556
DIABETES MELLITUS WITHOUT MENTION OF COMPLICATI...    504
ESSENTIAL HYPERTENSION                                471
UNSPECIFIED HYPOTHYROIDISM                            464
OBESITY, UNSPECIFIED                                  404
ANEMIA, UNSPECIFIED                                   372
MORBID OBESITY                                        365
CHRONIC ISCHEMIC HEART DISEASE                        345
HYPERTENSION, UNSPECIFIED                             333
HYPERTENSION, ESSENTIAL                               327
CHRONIC ISCHEMIC HEART DISEASE, UNSPECIFIED           306
DIABETES MELLITUS WITHOUT MENTION OF COMPLICATI...    297

--- Sample Rows (first 3) ---

   Patient     ICD9                                               Name
0      220 401.9000                 UNSPECIFIED ESSENTIAL HYPERTENSION
1      220   V58.61          LONG-TERM (CURRENT) USE OF ANTICOAGULANTS
2      220  79.3500  OPEN REDUCTION OF FRACTURE OF FEMUR WITH INTER...

==========================================================================================
DATASET: ניתוחים_260415
File: ניתוחים_260415.xlsx  |  Rows: 46,909  |  Cols: 44  |  Memory: 107.94 MB
Description: Surgery cases — procedures, timestamps, staff, anesthesia (likely central fact table)
==========================================================================================

--- Schema Summary ---

                     column           dtype  non_null_count  null_count  null_pct  n_unique  uniqueness_ratio
0              אחות מסתובבת          object           43781        3128    6.6700      2032            0.0464
1                אחות רחוצה          object           42868        4041    8.6100       760            0.0177
2                     מרדים          object           40282        6627   14.1300      1940            0.0482
3                 עוזר מנתח          object           16027       30882   65.8300       901            0.0562
4                       F45         float64               0       46909  100.0000         0               NaN
5                       F46         float64               0       46909  100.0000         0               NaN
6            Medical Record           int64           46909           0    0.0000     34537            0.7363
7                   patient           int64           46909           0    0.0000     28461            0.6067
8                       גיל         float64           46899          10    0.0200       108            0.0023
9               הערה לאבחנה          object           10987       35922   76.5800      7230            0.6581
10           הערה לפרוצדורה          object           10421       36488   77.7800      7175            0.6885
11              הרדמה פירוט          object             518       46391   98.9000       158            0.3050
12                      חדר          object           42611        4298    9.1600        11            0.0003
13                יום ניתוח          object           46909           0    0.0000         7            0.0001
14              מחלקה מנתחת          object           46909           0    0.0000         5            0.0001
15        מחלקה מנתחת נוספת          object             231       46678   99.5100        13            0.0563
16                      מין          object           46909           0    0.0000         2            0.0000
17               מנתח אחראי          object           45454        1455    3.1000       487            0.0107
18                מנתח ראשי          object           28654       18255   38.9200      1331            0.0465
19                מספר מקרה         float64           46908           1    0.0000     33500            0.7142
20                סוג הרדמה          object           46485         424    0.9000        15            0.0003
21                 סוג מקרה          object           46909           0    0.0000         2            0.0000
22                סוג ניתוח          object           46326         583    1.2400        12            0.0003
23  פעולה ניתוחית מיילדותית          object              13       46896   99.9700         1            0.0769
24              צד פרוצדורה          object           21390       25519   54.4000         3            0.0001
25                קוד אבחנה          object           40746        6163   13.1400      2199            0.0540
26             קוד פרוצדורה          object           44032        2877    6.1300      2219            0.0504
27                 שם אבחנה          object           40746        6163   13.1400      2792            0.0685
28              שם פרוצדורה          object           44032        2877    6.1300      2742            0.0623
29     שעת יציאה מחדר ניתוח          object           42776        4133    8.8100      1324            0.0310
30     שעת כניסה לחדר ניתוח          object           46509         400    0.8500      1299            0.0279
31           שעת סיום הרדמה          object           42963        3946    8.4100      1303            0.0303
32           שעת סיום ניתוח          object           46642         267    0.5700      1320            0.0283
33       שעת שחרור מח ניתוח          object           46907           2    0.0000      1327            0.0283
34          שעת תחילת הרדמה          object           45999         910    1.9400      1303            0.0283
35          שעת תחילת ניתוח          object           46909           0    0.0000      1299            0.0277
36   תאריך יציאה מחדר ניתוח  datetime64[ns]           42776        4133    8.8100      2000            0.0468
37   תאריך כניסה לחדר ניתוח  datetime64[ns]           46509         400    0.8500      2184            0.0470
38              תאריך ניתוח  datetime64[ns]           46909           0    0.0000      2184            0.0466
39         תאריך סיום הרדמה  datetime64[ns]           42963        3946    8.4100      2183            0.0508
40         תאריך סיום ניתוח  datetime64[ns]           46642         267    0.5700      2183            0.0468
41     תאריך שחרור מח ניתוח  datetime64[ns]           46907           2    0.0000      2183            0.0465
42        תאריך תחילת הרדמה  datetime64[ns]           45999         910    1.9400      2184            0.0475
43        תאריך תחילת ניתוח  datetime64[ns]           46909           0    0.0000      2184            0.0466

--- Potential Identifier Columns ---

           column  n_unique  uniqueness_ratio  null_count       reasons  pk_candidate
0  Medical Record     34537            0.7363           0  name_pattern         False
1       מספר מקרה     33500            0.7142           1  name_pattern         False
2         patient     28461            0.6067           0  name_pattern         False

--- Data Quality ---
Duplicate rows (full row): 0
No PK-candidate columns to check for duplicates.

--- Date Column Analysis ---

                    column                      min_date   max_date  n_unique_dates  null_count  parseable_pct
0              תאריך ניתוח 2020-01-20 00:00:00.000000000 2026-02-18            2184           0       100.0000
1                קוד אבחנה 1970-01-01 00:00:00.000000003 2065-06-25              31        7357        84.3200
2   תאריך כניסה לחדר ניתוח 2020-01-20 00:00:00.000000000 2026-02-18            2184         400        99.1500
3     שעת כניסה לחדר ניתוח                           NaT        NaT               0       46909         0.0000
4        תאריך תחילת ניתוח 2020-01-20 00:00:00.000000000 2026-02-18            2184           0       100.0000
5          שעת תחילת ניתוח                           NaT        NaT               0       46909         0.0000
6        תאריך תחילת הרדמה 2020-01-20 00:00:00.000000000 2026-02-18            2184         910        98.0600
7          שעת תחילת הרדמה                           NaT        NaT               0       46909         0.0000
8         תאריך סיום הרדמה 2020-01-20 00:00:00.000000000 2026-02-18            2183        3946        91.5900
9           שעת סיום הרדמה                           NaT        NaT               0       46909         0.0000
10        תאריך סיום ניתוח 2020-01-20 00:00:00.000000000 2026-02-18            2183         267        99.4300
11          שעת סיום ניתוח                           NaT        NaT               0       46909         0.0000
12  תאריך יציאה מחדר ניתוח 2020-07-20 00:00:00.000000000 2026-02-18            2000        4133        91.1900
13    שעת יציאה מחדר ניתוח                           NaT        NaT               0       46909         0.0000
14    תאריך שחרור מח ניתוח 2020-01-20 00:00:00.000000000 2026-02-18            2183           2       100.0000
15      שעת שחרור מח ניתוח                           NaT        NaT               0       46909         0.0000

--- Numeric Column Statistics ---

           column       count            mean            std          min          median             max
0       מספר מקרה 46,908.0000 13,299,078.5691 5,703,601.2277   4,093.0000 11,630,660.0000 32,474,177.0000
1  Medical Record 46,909.0000  1,914,115.0190   979,483.6865 344,918.0000  1,863,142.0000  3,714,618.0000
2             גיל 46,899.0000         50.8398        22.9830       1.0000         52.0000        111.0000
3             F45      0.0000             NaN            NaN          NaN             NaN             NaN
4             F46      0.0000             NaN            NaN          NaN             NaN             NaN
5         patient 46,909.0000    285,332.3838   194,034.4285     220.0000    267,175.0000    794,504.0000

--- Categorical Column Analysis (Top 20) ---

  Column: מין  |  Unique categories: 2

      count
מין
זכר   27387
נקבה  19522

  Column: סוג מקרה  |  Unique categories: 2

           count
סוג מקרה
אשפוז      42834
אמבולטורי   4075

  Column: יום ניתוח  |  Unique categories: 7

           count
יום ניתוח
ראשון      10014
שלישי       8923
שני         8277
רביעי       7945
חמישי       7677
שישי        2292
שבת         1781

  Column: מחלקה מנתחת  |  Unique categories: 5

              count
מחלקה מנתחת
כירורגיה א     9977
אורטופדיה ב    9906
אורטופדיה א    9157
אף אוזן גרון   8953
כירורגיה ב     8916

  Column: מחלקה מנתחת נוספת  |  Unique categories: 13

                   count
מחלקה מנתחת נוספת
NaN                46678
אורטופדיה ב           78
אורטופדיה א           30
אורולוגיה             27
כלי דם                19
אף אוזן גרון          17
כירורגיה א            16
פלסטיקה               15
כירורגיה ב            13
כירורגיה ילדים         5
אחר                    4
גסטרו                  3
פנימית א               2
נשים                   2

  Column: חדר  |  Unique categories: 11

            count
חדר
חדר 4        8876
חדר 3        8868
חדר 6        7770
חדר 1        5885
חדר 2        5055
NaN          4298
חדר 7        3650
חדר 5        1939
חדר 8         205
חדר 9         178
חדר 10        177
ניתוחי חוץ      8

  Column: קוד פרוצדורה  |  Unique categories: 2,219
  Note: High cardinality (2219 categories) — showing top 20 only

              count
קוד פרוצדורה
NaN            2877
47.01          1947
51.23          1679
21.69.05       1153
79.15          1074
03.09.04        930
21.88           819
99.21           793
49.01           736
54.11           709
86.22           539
79.32           533
22.19.02        528
79.36           517
81.54           514
93.53           483
4.43            470
49.46           470
80.26           429
28.3            416

  Column: שם פרוצדורה  |  Unique categories: 2,742
  Note: High cardinality (2742 categories) — showing top 20 only

                                                   count
שם פרוצדורה
NaN                                                 2877
LAPAROSCOPIC APPENDECTOMY                           1947
LAPAROSCOPIC CHOLECYSTECTOMY                        1679
PARTIAL TURBINECTOMY                                1153
FACETECTOMY- LUMBAR                                  930
CLOSED RED-INT FIX FEMUR                             825
EXPLORATORY LAPAROTOMY                               631
SEPTOPLASTY NEC                                      623
INCISION & DRAINAGE PERIANAL ABSCESS                 530
TOTAL KNEE REPLACEMENT                               514
INJECT ANTIBIOTIC                                    480
TONSILLECTOMY WITH ADENOIDECTOMY                     416
F.E.S.S (FUNCTIONING ENDOSCOPIC SINUS DIAGNOSTIC)    415
DRAINAGE ABSCESS                                     412
OPN RED-INT FIX RAD/ULNA                             391
HEMORRHOIDECTOMY                                     387
CARPAL TUNNEL RELEASE                                386
OP RED-INT FIX TIB/FIBUL                             375
TOTAL HIP REPLACEMENT                                336
SPINAL FUSION NOS                                    309

  Column: הערה לפרוצדורה  |  Unique categories: 7,175
  Note: High cardinality (7175 categories) — showing top 20 only

                              count
הערה לפרוצדורה
NaN                           36488
L4-5                            191
WITH ACUMED PLATE AND SCREWS     84
with mesh                        80
L3-4                             62
L5-S1                            61
PPH HEMORRHOIDOPEXY              51
5TH                              40
TFNA                             37
RTAPP                            36
PARTIAL                          34
WITH MESH                        30
SLEEP ENDOSCOPY                  28
R-TAPP                           27
KNEE                             26
LEG                              26
partial                          24
POSTERIOR                        24
PPH                              23
DISE                             21

  Column: צד פרוצדורה  |  Unique categories: 3

             count
צד פרוצדורה
NaN          25519
Right         9430
Left          9302
BOTH          2658

  Column: קוד אבחנה  |  Unique categories: 2,199
  Note: High cardinality (2199 categories) — showing top 20 only

           count
קוד אבחנה
NaN         6163
540.9       1846
566         1345
478         1203
470         1145
574.2       1142
820.21       873
550.9        848
354          469
553.1        438
729.5        437
327.23       435
474.1        404
278.01       391
565          385
820.09       384
473.8        378
682.9        358
239.2        357
553.21       345

  Column: שם אבחנה  |  Unique categories: 2,792
  Note: High cardinality (2792 categories) — showing top 20 only

                                                    count
שם אבחנה
NaN                                                  6163
ACUTE APPENDICITIS WITHOUT MENTION OF PERITONITIS    1403
ABSCESS OF ANAL AND RECTAL REGIONS                   1344
HYPERTROPHY OF NASAL TURBINATES                       809
DEVIATED NASAL SEPTUM                                 776
CLOSED FRACTURE OF INTERTROCHANTERIC SECTION OF...    524
UNILATERAL OR UNSPECIFIED INGUINAL HERNIA, WITH...    507
ACUTE APPENDICITIS                                    443
PAIN IN LIMB                                          407
Hypertrophy of nasal turbinates                       394
MORBID OBESITY                                        388
Deviated nasal septum                                 369
CELLULITIS AND ABSCESS OF UNSPECIFIED SITES           354
CALCULUS OF GALLBLADDER WITHOUT CHOLECYSTITIS         353
NEOPLASM OF UNSPECIFIED NATURE OF BONE, SOFT TI...    351
INCISIONAL HERNIA WITHOUT MENTION OF OBSTRUCTIO...    337
INGUINAL HERNIA                                       334
PILONIDAL CYST WITHOUT MENTION OF ABSCESS             333
PILONIDAL CYST WITH ABSCESS                           330
ANAL FISSURE                                          313

  Column: הערה לאבחנה  |  Unique categories: 7,230
  Note: High cardinality (7230 categories) — showing top 20 only

                  count
הערה לאבחנה
NaN               35922
L4-5                176
KNEE                 91
L5-S1                66
POSTERIOR            60
L3-4                 55
SUSPECTED            47
RECURRENT            44
GANGRENOUS           29
INDIRECT             28
GROIN                28
FOOT                 27
suspected            27
HIP                  27
ANTERIOR             25
THUMB                24
gangrenous           24
PERIANAL ABSCESS     24
SUBCAPITAL           24
BLEEDING             23

  Column: שעת כניסה לחדר ניתוח  |  Unique categories: 1,299
  Note: High cardinality (1299 categories) — showing top 20 only

                      count
שעת כניסה לחדר ניתוח
07:50:00                616
07:45:00                522
08:00:00                459
07:40:00                423
NaN                     400
07:55:00                342
15:05:00                322
07:48:00                314
07:44:00                311
07:52:00                297
07:42:00                291
07:46:00                280
07:47:00                264
07:43:00                256
07:53:00                249
07:49:00                242
07:41:00                228
15:10:00                225
08:10:00                211
07:54:00                209

  Column: שעת תחילת ניתוח  |  Unique categories: 1,299
  Note: High cardinality (1299 categories) — showing top 20 only

                 count
שעת תחילת ניתוח
08:30:00           306
08:40:00           286
08:50:00           261
09:00:00           247
08:25:00           217
08:35:00           216
08:20:00           206
08:45:00           205
08:42:00           184
08:55:00           173
08:48:00           172
08:15:00           172
08:27:00           171
08:28:00           167
08:34:00           165
08:36:00           162
08:31:00           162
08:37:00           160
08:32:00           158
08:22:00           158

  Column: שעת תחילת הרדמה  |  Unique categories: 1,303
  Note: High cardinality (1303 categories) — showing top 20 only

                 count
שעת תחילת הרדמה
NaN                910
08:00:00           801
08:10:00           462
08:05:00           448
07:55:00           341
08:15:00           322
07:50:00           320
08:02:00           257
08:03:00           252
15:10:00           244
08:20:00           238
07:57:00           235
08:01:00           234
15:15:00           230
08:04:00           224
07:54:00           222
08:08:00           219
08:07:00           216
07:58:00           215
07:56:00           206

  Column: שעת סיום הרדמה  |  Unique categories: 1,303
  Note: High cardinality (1303 categories) — showing top 20 only

                count
שעת סיום הרדמה
NaN              3946
13:00:00          109
10:38:00          103
11:25:00          101
12:50:00          100
10:30:00           97
11:00:00           95
13:42:00           95
10:50:00           93
11:43:00           93
14:10:00           92
10:54:00           92
12:15:00           92
12:46:00           91
15:42:00           91
14:38:00           88
14:32:00           88
12:30:00           88
10:12:00           86
10:25:00           86

  Column: שעת סיום ניתוח  |  Unique categories: 1,320
  Note: High cardinality (1320 categories) — showing top 20 only

                count
שעת סיום ניתוח
NaN               267
14:30:00          133
11:00:00          133
12:00:00          126
13:20:00          126
14:10:00          123
14:00:00          119
10:10:00          117
11:25:00          113
16:00:00          111
11:40:00          111
10:12:00          108
12:20:00          107
13:00:00          105
10:20:00          105
12:40:00          104
10:50:00          103
13:25:00          103
14:20:00          102
09:30:00          101

  Column: שעת יציאה מחדר ניתוח  |  Unique categories: 1,324
  Note: High cardinality (1324 categories) — showing top 20 only

                      count
שעת יציאה מחדר ניתוח
NaN                    4133
11:02:00                 96
10:29:00                 96
12:31:00                 95
12:58:00                 93
12:05:00                 93
12:18:00                 91
10:51:00                 91
12:48:00                 90
10:40:00                 90
13:56:00                 89
10:16:00                 88
10:53:00                 86
10:43:00                 86
13:43:00                 85
11:26:00                 85
13:41:00                 85
14:41:00                 85
11:20:00                 85
11:07:00                 85

  Column: שעת שחרור מח ניתוח  |  Unique categories: 1,327
  Note: High cardinality (1327 categories) — showing top 20 only

                    count
שעת שחרור מח ניתוח
11:02:00              112
12:18:00              110
14:20:00              106
13:56:00              105
10:44:00              104
10:16:00              103
12:32:00              103
11:24:00               99
11:07:00               99
13:41:00               98
14:33:00               98
13:09:00               97
11:31:00               96
12:05:00               95
13:38:00               95
12:34:00               93
12:39:00               92
10:51:00               92
14:43:00               92
11:56:00               92

  Column: סוג ניתוח  |  Unique categories: 12

                          count
סוג ניתוח
אלקטיבי                   24986
דחוף                      14730
ססיה                       6113
NaN                         583
בהול                        339
פעולה לא ניתוחית             98
אלקטיבי,ססיה                 36
אלקטיבי + ססיה               10
דחוף,ססיה                     4
קציר איברים                   4
אלקטיבי,פעולה לא ניתוחית      4
אלקטיבי,קציר איברים           1
דחוף,פעולה לא ניתוחית         1

  Column: פעולה ניתוחית מיילדותית  |  Unique categories: 1

                         count
פעולה ניתוחית מיילדותית
NaN                      46896
בוצע ניתוח קיסרי            13

  Column: סוג הרדמה  |  Unique categories: 15

                    count
סוג הרדמה
General             38217
Sedation             2307
Local                1772
General + Local      1184
General + Regional   1079
Spinal                818
Other                 597
NaN                   424
Regional              322
Spinal + Epidural      98
Local + Regional       33
Epidural               24
General, Regional      16
General, Local          9
Regional, Sedation      5
Local, Sedation         4

  Column: הרדמה פירוט  |  Unique categories: 158

                     count
הרדמה פירוט
NaN                  46391
SEDATION                60
sedation                60
GENERAL + PNB           26
סדציה                   21
spinal + sedation       20
MAC                     13
SPINAL + SEDATION       12
Spinal + Sedation       10
general + epidural       9
SEDATION + LOCAL         9
regional + sedation      9
sedation + local         9
התפחה                    9
general + PNB            8
LOCAL + SEDATION         6
TUMESCENT                5
sedation+local           5
mac                      5
local + sedation         5

  Column: מנתח אחראי  |  Unique categories: 487

                         count
מנתח אחראי
דר' שדמי נורית            3320
דר' טאהא מוחמד            2963
דר' קירשון מרק            2737
דר' יונס מחמד             1719
דר' ארנוביץ' דוד          1569
פרופ' ברוורמן יצחק        1537
NaN                       1455
דר' גזמאוי ג'מאל          1424
דר' גרנות בועז            1411
דר' גרינבלט גולדה         1193
דר' זילברמינץ ויאציסלב    1169
דר' קורין אלכסנדר         1162
דר' ויוננקו אלכסנדר        945
דר' חדש אורי               827
דר' יונס עורוואה           813
דר' קרן עמית               783
דר' שפירא עמיר             771
דר' קוצ'ר יורי             760
דר' חיימוביץ ליעד-ברוך     750
דר' שפר דניאל              700

  Column: מנתח ראשי  |  Unique categories: 1,331
  Note: High cardinality (1331 categories) — showing top 20 only

                         count
מנתח ראשי
NaN                      18255
דר' טייטלבאום טלי          768
דר' איגנטנקו אוליסה        735
דר' שפר דניאל              727
דר' טשרנין ניב             636
דר' גריבץ טיאוסנו ילנה     570
דר' שמולביץ' ארתיום        566
דר' מצארווה היית'ם         537
דר' קרן עמית               514
דר' קקיאשוילי יוסי         509
דר' פלורס חואן לואיס       472
דר' יונס סעיד              441
דר' אכתילאת עובידה         429
דר' ואסקז אוסקר            421
דר' ברקאי שליו סיון        399
דר' דראושה מחמוד           391
דר' יונס גמאל              388
דר' לוי שחר הגר            386
 זועבי נרדין               381
דר' מעיין דור              379

  Column:  עוזר מנתח  |  Unique categories: 901
  Note: High cardinality (901 categories) — showing top 20 only

                              count
 עוזר מנתח
NaN                           30882
דר' פלורס חואן לואיס            758
דר' איגנטנקו אוליסה             585
דר' טשרנין ניב                  531
דר' יונס סעיד                   493
דר' אלגבסי מירי                 429
דר' סורטו טטיאנה                371
דר' סטלר הילה                   356
דר' גריבץ טיאוסנו ילנה          351
דר' לוי שחר הגר                 349
דר' קמריו ספדה חררדו גבריאל     336
דר' פאינזילבר גולדמן יפעת       335
דר' שפר דניאל                   306
דר' פארן מאיה                   256
דר' יונס גמאל                   251
דר' סמארה סלים                  234
דר' ואצל גמאל                   233
דר' טייטלבאום טלי               215
דר' פינקל בנימין                209
דר' ואסקז אוסקר                 207

  Column:  אחות רחוצה  |  Unique categories: 760
  Note: High cardinality (760 categories) — showing top 20 only

                       count
 אחות רחוצה
NaN                     4041
 טרוגמן אלה             2258
 רוזנטל גיורגי          2101
 קרבליקוב ולדימיר       1869
 מסאלחה סאאל            1556
 פפרנוב יוליה           1508
 וותד וואסים            1385
 אוחיון דלנה            1278
 אבו עסבה רפעת          1226
 קורבי רביע             1223
 אבו עקל חמד            1217
 אירמייב אוקסנה         1149
 טקצ'מן אלכסנדר         1133
 מחאמיד בילל            1128
 יחזקאל חיים            1104
 עבד אלסלאם עומר        1096
 עבד אלג'ואד מוחמד      1048
 נסראללה מחאג'נה        1043
 בואקני אקרם            1017
 יוסיפוב שומינוב יעל    1016

  Column:  אחות מסתובבת  |  Unique categories: 2,032
  Note: High cardinality (2032 categories) — showing top 20 only

                    count
 אחות מסתובבת
NaN                  3128
 יחזקאל חיים         2676
 אירמייב אוקסנה      2138
 מסאלחה סאאל         1731
 פפרנוב יוליה        1653
 דוברומילסקי קטיה    1558
 בואקני אקרם         1443
 דוידוב פרט          1271
 טקצ'מן אלכסנדר      1256
 טרוגמן אלה          1188
 נסראללה מחאג'נה     1135
 וותד וואסים         1129
 אבו עסבה רפעת       1109
 אברמוביץ' יפה       1101
 טרייבר דניאל        1016
 רוזנטל גיורגי        957
 אבו עקל חמד          852
 לבנאוי יאסר          836
 שיח זייד סלים        771
 אנקוה ליאת           750

  Column:  מרדים  |  Unique categories: 1,940
  Note: High cardinality (1940 categories) — showing top 20 only

                      count
 מרדים
NaN                    6627
דר' ג'לג'וליה חוסאם    1772
דר' אברמוב ויטלי       1704
דר' קעדאן מוחמד        1389
דר' נאסר מוחמד         1387
דר' חלאג' ג'מאל        1349
דר' מגידיי אנטולי      1329
דר' עאסי רים           1198
דר' חמודה מוסלם        1175
דר' חטיב וליד          1123
דר' חסדיה מוחמד        1007
דר' גורדון מיכאל       1002
דר' אניאנוב מקסים       908
דר' גבאס אחמד           838
דר' דראוושה מייס        809
דר' אבו כאלאף פאטמה     804
דר' מחאג'נה היבא        767
דר' צ'רנוב פבל          635
דר' גור צבר             620
דר' מולק ארמנד דוד      611

--- Sample Rows (first 3) ---

,מספר מקרה,Medical Record,גיל,מין,סוג מקרה,תאריך ניתוח,יום ניתוח,מחלקה מנתחת,מחלקה מנתחת נוספת,חדר,קוד פרוצדורה,שם פרוצדורה,הערה לפרוצדורה,צד פרוצדורה,קוד אבחנה,שם אבחנה,הערה לאבחנה,תאריך כניסה לחדר ניתוח,שעת כניסה לחדר ניתוח,תאריך תחילת ניתוח,שעת תחילת ניתוח,תאריך תחילת הרדמה,שעת תחילת הרדמה,תאריך סיום הרדמה,שעת סיום הרדמה,תאריך סיום ניתוח,שעת סיום ניתוח,תאריך יציאה מחדר ניתוח,שעת יציאה מחדר ניתוח,תאריך שחרור מח ניתוח,שעת שחרור מח ניתוח,סוג ניתוח,פעולה ניתוחית מיילדותית,סוג הרדמה,הרדמה פירוט,מנתח אחראי,מנתח ראשי,עוזר מנתח,אחות רחוצה,אחות מסתובבת,מרדים,F45,F46,patient
0,"11,642,461.0000",2084001,22.0000,זכר,אשפוז,2023-07-03,שני,אף אוזן גרון,NaN,חדר 7,21.69.05,PARTIAL TURBINECTOMY,NaN,NaN,470,DEVIATED NASAL SEPTUM,NASAL POLYPS?,2023-07-03,11:06:00,2023-07-03,11:32:00,2023-07-03,11:10:00,2023-07-03,12:50:00,2023-07-03,12:42:00,2023-07-03,12:54:00,2023-07-03,12:55:00,אלקטיבי,NaN,General,NaN,דר' מעיין דור,דר' חג'וג' מג'ד,NaN,אוחיון דלנה,אברמוביץ' יפה,דר' גבאס אחמד,NaN,NaN,447553
1,"11,642,461.0000",2084001,22.0000,זכר,אשפוז,2023-07-03,שני,אף אוזן גרון,NaN,חדר 7,21.8800,SEPTOPLASTY NEC,NaN,NaN,478,HYPERTROPHY OF NASAL TURBINATES,NaN,2023-07-03,11:06:00,2023-07-03,11:32:00,2023-07-03,11:10:00,2023-07-03,12:50:00,2023-07-03,12:42:00,2023-07-03,12:54:00,2023-07-03,12:55:00,אלקטיבי,NaN,General,NaN,דר' מעיין דור,דר' חג'וג' מג'ד,NaN,אוחיון דלנה,אברמוביץ' יפה,דר' גבאס אחמד,NaN,NaN,447553
2,"11,641,706.0000",2083920,9.0000,נקבה,אשפוז,2023-07-03,שני,אף אוזן גרון,NaN,חדר 7,21.8800,SEPTOPLASTY NEC,NaN,NaN,NaN,NaN,NaN,2023-07-03,07:47:00,2023-07-03,08:16:00,2023-07-03,07:56:00,2023-07-03,09:24:00,2023-07-03,09:18:00,2023-07-03,09:29:00,2023-07-03,09:29:00,אלקטיבי,NaN,General,NaN,"דר' מעיין דור ,דר' חג'וג' מג'ד",פרופ' ברוורמן יצחק,NaN,אוחיון דלנה,אברמוביץ' יפה,"דר' נעמה ח'אלד ,דר' גבאס אחמד",NaN,NaN,1280

==========================================================================================
DATASET: סוג דם גובה משקל BMI
File: סוג דם גובה משקל BMI.xlsx  |  Rows: 34,521  |  Cols: 7  |  Memory: 3.22 MB
Description: Patient vitals: blood type, height, weight, BMI per case
==========================================================================================

--- Schema Summary ---

        column           dtype  non_null_count  null_count  null_pct  n_unique  uniqueness_ratio
0          BMI         float64           27290        7231   20.9500      3720            0.1363
1      Patient           int64           34521           0    0.0000     28461            0.8245
2         גובה         float64           27294        7227   20.9400       143            0.0052
3           דם          object           15257       19264   55.8000        11            0.0007
4    מספר מקרה         float64           34520           1    0.0000     33500            0.9705
5         משקל         float64           32655        1866    5.4100       670            0.0205
6  תאריך ניתוח  datetime64[ns]           34521           0    0.0000      2184            0.0633

--- Potential Identifier Columns ---

      column  n_unique  uniqueness_ratio  null_count                        reasons  pk_candidate
0  מספר מקרה     33500            0.9705           1  name_pattern, high_uniqueness         False
1    Patient     28461            0.8245           0                   name_pattern         False

--- Data Quality ---
Duplicate rows (full row): 0
No PK-candidate columns to check for duplicates.

--- Date Column Analysis ---

        column   min_date   max_date  n_unique_dates  null_count  parseable_pct
0  תאריך ניתוח 2020-01-20 2026-02-18            2184           0       100.0000

--- Numeric Column Statistics ---

      column       count            mean            std        min          median             max
0    Patient 34,521.0000    282,653.9047   193,069.5258   220.0000    264,585.0000    794,504.0000
1  מספר מקרה 34,520.0000 13,527,072.2570 6,024,398.4476 4,093.0000 11,631,578.0000 32,474,177.0000
2       גובה 27,294.0000        168.4932        11.7669     0.0000        170.0000        206.0000
3       משקל 32,655.0000         76.0030       104.4441     0.9300         75.0000     13,336.9000
4        BMI 27,290.0000        160.1130     7,667.2585     3.1111         26.5285    840,000.0000

--- Categorical Column Analysis (Top 20) ---

  Column: דם  |  Unique categories: 11

         count
דם
NaN      19264
A POS     5363
O POS     5111
B POS     2475
AB POS     895
A NEG      548
O NEG      500
B NEG      262
AB NEG      93
A2B POS      5
A2 POS       3
A2 NEG       2

--- Sample Rows (first 3) ---

   Patient תאריך ניתוח       מספר מקרה     גובה    משקל     BMI     דם
0   100343  2020-05-24 11,071,228.0000 182.0000 89.0000 26.8687  B POS
1   100349  2025-09-28 11,976,373.0000      NaN 95.0000     NaN  A POS
2   100352  2020-05-19 11,070,099.0000 175.0000 73.0000 23.8367    NaN

==========================================================================================
DATASET: סטורציה
File: סטורציה.xlsx  |  Rows: 27,625  |  Cols: 4  |  Memory: 0.88 MB
Description: Pre-operative oxygen saturation per case
==========================================================================================

--- Schema Summary ---

               column           dtype  non_null_count  null_count  null_pct  n_unique  uniqueness_ratio
0             Patient           int64           27625           0    0.0000     23143            0.8378
1                מקרה           int64           27625           0    0.0000     26615            0.9634
2  סטורציה לפני ניתוח         float64           27601          24    0.0900        39            0.0014
3         תאריך ניתוח  datetime64[ns]           27625           0    0.0000      2182            0.0790

--- Potential Identifier Columns ---

    column  n_unique  uniqueness_ratio  null_count                        reasons  pk_candidate
0     מקרה     26615            0.9634           0  name_pattern, high_uniqueness          True
1  Patient     23143            0.8378           0                   name_pattern         False

--- Data Quality ---
Duplicate rows (full row): 0

  column  rows_in_duplicate_groups  is_unique
0   מקרה                      1780      False

--- Date Column Analysis ---

        column   min_date   max_date  n_unique_dates  null_count  parseable_pct
0  תאריך ניתוח 2020-01-20 2026-02-18            2182           0       100.0000

--- Numeric Column Statistics ---

               column       count            mean            std        min          median             max
0             Patient 27,625.0000    276,745.6243   188,973.9766   220.0000    260,836.0000    794,504.0000
1                מקרה 27,625.0000 13,146,370.5908 5,530,650.7908 4,093.0000 11,586,441.0000 32,473,527.0000
2  סטורציה לפני ניתוח 27,601.0000         97.9875         6.2301     0.0000         98.0000        987.0000

--- Categorical Column Analysis (Top 20) ---
No categorical (object) columns.

--- Sample Rows (first 3) ---

   Patient      מקרה  סטורציה לפני ניתוח תאריך ניתוח
0   107930  11963396             98.0000  2025-09-01
1    68570  11537684             95.0000  2022-10-24
2   185129  11078527             98.0000  2020-06-16

==========================================================================================
DATASET: עישון
File: עישון.xlsx  |  Rows: 31,661  |  Cols: 4  |  Memory: 1.01 MB
Description: Smoking status per surgery case
==========================================================================================

--- Schema Summary ---

       column           dtype  non_null_count  null_count  null_pct  n_unique  uniqueness_ratio
0     Patient           int64           31661           0    0.0000     25626            0.8094
1     Smoking         float64           31385         276    0.8700         3            0.0001
2  מועד ניתוח  datetime64[ns]           31661           0    0.0000     29994            0.9473
3   מספר מקרה         float64           31658           3    0.0100     29659            0.9369

--- Potential Identifier Columns ---

      column  n_unique  uniqueness_ratio  null_count                        reasons  pk_candidate
0  מספר מקרה     29659            0.9369           3  name_pattern, high_uniqueness         False
1    Patient     25626            0.8094           0                   name_pattern         False

--- Data Quality ---
Duplicate rows (full row): 0
No PK-candidate columns to check for duplicates.

--- Date Column Analysis ---

       column            min_date            max_date  n_unique_dates  null_count  parseable_pct
0  מועד ניתוח 2020-01-20 07:38:00 2026-02-18 11:33:00            2184           0       100.0000

--- Numeric Column Statistics ---

      column       count            mean            std        min          median             max
0    Patient 31,661.0000    284,936.0658   194,024.4108   220.0000    267,146.0000    794,504.0000
1  מספר מקרה 31,658.0000 12,495,370.6829 4,280,988.6518 4,093.0000 11,607,876.5000 32,474,177.0000
2    Smoking 31,385.0000          1.7138         0.4908     1.0000          2.0000          3.0000

--- Categorical Column Analysis (Top 20) ---
No categorical (object) columns.

--- Sample Rows (first 3) ---

   Patient       מספר מקרה          מועד ניתוח  Smoking
0   348295 11,432,846.0000 2022-02-08 21:15:00   2.0000
1   701394 11,876,662.0000 2025-02-09 18:34:00   3.0000
2    61493 11,770,783.0000 2024-05-20 08:16:00   2.0000

==========================================================================================
DATASET: צוות סיעודי בניתוח
File: צוות סיעודי בניתוח.xlsx  |  Rows: 32,831  |  Cols: 3  |  Memory: 4.86 MB
Description: Scrub nurse assignments per case (may be multi-valued)
==========================================================================================

--- Schema Summary ---

       column    dtype  non_null_count  null_count  null_pct  n_unique  uniqueness_ratio
0     Patient    int64           32831           0    0.0000     26200            0.7980
1  אחות רחוצה   object           32831           0    0.0000        80            0.0024
2   מספר מקרה  float64           32824           7    0.0200     30476            0.9285

--- Potential Identifier Columns ---

      column  n_unique  uniqueness_ratio  null_count                        reasons  pk_candidate
0  מספר מקרה     30476            0.9285           7  name_pattern, high_uniqueness         False
1    Patient     26200            0.7980           0                   name_pattern         False

--- Data Quality ---
Duplicate rows (full row): 0
No PK-candidate columns to check for duplicates.

--- Date Column Analysis ---
No date columns detected.

--- Numeric Column Statistics ---

      column       count            mean            std        min          median             max
0    Patient 32,831.0000    284,987.5858   194,990.0389   220.0000    265,253.0000    794,504.0000
1  מספר מקרה 32,824.0000 13,383,931.9415 5,804,205.5777 4,093.0000 11,642,574.5000 32,474,177.0000

--- Categorical Column Analysis (Top 20) ---

  Column: אחות רחוצה  |  Unique categories: 80

                   count
אחות רחוצה
רוזנטל גיורגי       1693
קרבליקוב ולדימיר    1549
טרוגמן אלה          1498
מסאלחה סאאל         1258
וותד וואסים         1190
פפרנוב יוליה        1106
אבו עסבה רפעת       1075
אבו עקל חמד          988
קורבי רביע           966
טקצ'מן אלכסנדר       957
מחאמיד בילל          944
אירמייב אוקסנה       941
אוחיון דלנה          920
עבד אלג'ואד מוחמד    887
יחזקאל חיים          881
נסראללה מחאג'נה      871
בואקני אקרם          855
עבד אלסלאם עומר      841
ספקטור אנה           795
טרייבר דניאל         787

--- Sample Rows (first 3) ---

   Patient       מספר מקרה    אחות רחוצה
0   100020 11,529,175.0000    טרוגמן אלה
1   100020 11,529,175.0000  פפרנוב יוליה
2   100021 11,604,766.0000   אבו עקל חמד

==========================================================================================
DATASET: רגישות אחרת
File: רגישות אחרת.xlsx  |  Rows: 1,782  |  Cols: 4  |  Memory: 0.3 MB
Description: Other allergies/sensitivities (patient-level)
==========================================================================================

--- Schema Summary ---

       column           dtype  non_null_count  null_count  null_pct  n_unique  uniqueness_ratio
0     Patient           int64            1782           0    0.0000      1395            0.7828
1       הערות          object             423        1359   76.2600       315            0.7447
2  מועד כתיבה  datetime64[ns]            1782           0    0.0000      1782            1.0000
3      רגישות          object            1782           0    0.0000        47            0.0264

--- Potential Identifier Columns ---

    column  n_unique  uniqueness_ratio  null_count       reasons  pk_candidate
0  Patient      1395            0.7828           0  name_pattern         False

--- Data Quality ---
Duplicate rows (full row): 0
No PK-candidate columns to check for duplicates.

--- Date Column Analysis ---

       column                min_date                max_date  n_unique_dates  null_count  parseable_pct
0  מועד כתיבה 2018-01-30 21:21:30.330 2026-02-18 08:51:35.013            1059           0       100.0000

--- Numeric Column Statistics ---

    column      count         mean          std      min       median          max
0  Patient 1,782.0000 275,860.2256 197,932.8893 319.0000 252,003.0000 790,905.0000

--- Categorical Column Analysis (Top 20) ---

  Column: רגישות  |  Unique categories: 47

                 count
רגישות
אחר                512
קרדית אבק הבית     145
מוצרי חלב          138
G6PD Deficiency    138
גלוטן              100
מזון                90
פירות               79
דבורים              59
חתולים              57
צמחים               51
אגוזים              39
דגים                39
דשא                 36
בוטנים              36
לטקס                34
זיתים               31
ביצים               25
חלב פרה             24
שומשום              16
כלבים               13

  Column: הערות  |  Unique categories: 315

               count
הערות
NaN             1359
אבק               19
אפרסק             11
לקטוז             10
דבש                9
פול                8
יוד                8
מנגו               7
רספרים             6
פירות ים           5
גלוטן              4
ניקל               4
חציל               4
אננס               4
מתכת               3
בננה               3
מוקסיפן            3
ללא גלוטן          3
חומרים משמרים      2
פסטרמה             2

--- Sample Rows (first 3) ---

   Patient           רגישות הערות              מועד כתיבה
0   100615  G6PD Deficiency   NaN 2023-05-03 13:05:08.520
1   100966            צמחים   NaN 2023-01-17 11:39:35.963
2   101185            ביצים   NaN 2024-07-05 07:17:04.950

==========================================================================================
DATASET: רגישות לתרופות
File: רגישות לתרופות.xlsx  |  Rows: 8,820  |  Cols: 3  |  Memory: 0.78 MB
Description: Drug allergies/sensitivities (patient-level)
==========================================================================================

--- Schema Summary ---

       column           dtype  non_null_count  null_count  null_pct  n_unique  uniqueness_ratio
0   Drug_Name          object            8820           0    0.0000      1074            0.1218
1  Entry_Date  datetime64[ns]            8820           0    0.0000      8820            1.0000
2     Patient           int64            8820           0    0.0000      5196            0.5891

--- Potential Identifier Columns ---

    column  n_unique  uniqueness_ratio  null_count       reasons  pk_candidate
0  Patient      5196            0.5891           0  name_pattern         False

--- Data Quality ---
Duplicate rows (full row): 0
No PK-candidate columns to check for duplicates.

--- Date Column Analysis ---

       column                min_date                max_date  n_unique_dates  null_count  parseable_pct
0  Entry_Date 2018-01-13 01:42:01.077 2026-02-17 09:56:16.543            2140           0       100.0000

--- Numeric Column Statistics ---

    column      count         mean          std      min       median          max
0  Patient 8,820.0000 230,104.8610 184,238.3121 220.0000 182,932.0000 794,504.0000

--- Categorical Column Analysis (Top 20) ---

  Column: Drug_Name  |  Unique categories: 1,074
  Note: High cardinality (1074 categories) — showing top 20 only

                                 count
Drug_Name
PENICILLIN                        1060
OPTALGIN CPL 500MG                 471
IODINE                             470
G6PD deficiency                    234
AUGMENTIN BID TAB 875MG            225
OPTALGIN TAB 500MG                 180
ASPIRIN                            137
ETOPAN 500 MG                      123
MOXYPEN CAP 250MG                  120
ZINNAT TAB 500MG                   101
SULFA                               97
PENICILLINS                         94
NSAIDs                              93
ACAMOL CPL 500MG                    82
SIMVASTATIN                         77
VOLTAREN INJ 75MG/3ML 3ML           69
AUGMENTIN TAB 500MG                 69
OPTALGIN DRP 500MG/1ML BOT 10ML     59
VOLTAREN TAB 100MG                  59
AMLODIPINE                          58

--- Sample Rows (first 3) ---

   Patient   Drug_Name              Entry_Date
0      220      IODINE 2022-01-27 13:32:18.953
1      220   DIACEREIN 2022-01-27 13:35:14.423
2      226  GABAPENTIN 2019-05-26 09:38:55.460

==========================================================================================
DATASET: תרופות בניתוח
File: תרופות בניתוח.xlsx  |  Rows: 319,950  |  Cols: 4  |  Memory: 51.29 MB
Description: Medications administered during surgery (long format)
==========================================================================================

--- Schema Summary ---

      column    dtype  non_null_count  null_count  null_pct  n_unique  uniqueness_ratio
0    Patient    int64          319950           0    0.0000     27185            0.0850
1   אופן מתן   object          319950           0    0.0000        21            0.0001
2  מספר מקרה  float64          319941           9    0.0000     31791            0.0994
3      תרופה   object          319950           0    0.0000       306            0.0010

--- Potential Identifier Columns ---

      column  n_unique  uniqueness_ratio  null_count       reasons  pk_candidate
0  מספר מקרה     31791            0.0994           9  name_pattern         False
1    Patient     27185            0.0850           0  name_pattern         False

--- Data Quality ---
Duplicate rows (full row): 0
No PK-candidate columns to check for duplicates.

--- Date Column Analysis ---
No date columns detected.

--- Numeric Column Statistics ---

      column        count            mean            std        min          median             max
0    Patient 319,950.0000    287,009.8283   195,260.3674   220.0000    267,864.0000    794,504.0000
1  מספר מקרה 319,941.0000 12,294,453.7424 3,809,060.6971 4,093.0000 11,611,034.0000 32,474,177.0000

--- Categorical Column Analysis (Top 20) ---

  Column: תרופה  |  Unique categories: 306

                                                  count
תרופה
FENTANYL INJ 0.1 mg/2mL                           31130
PROPOFOL-LIPURO INJ 10MG/ML 20ML                  27321
LACTATED RINGER SOLUTION INJ 1000ML               26164
PARACETAMOL 1G INJECTION                          21343
SODIUM CHLORIDE (SALINE) INJ 0.9% 10ML            19425
CEFAMEZINE INJ 1G                                 16544
ESMERON INJ 50MG/5ML                              15258
ONDANSETRON INOVAMED AMP 8mg/4mL                  12565
PRAMIN INJ 10MG/2ML                               12002
PETHIDINE 100MG DOLESTIN                          10553
Ketorolac 30mg/ml Solution for Injection           9075
MIDOLAM INJ 5MG/5ML                                8459
MORPHINE HCL INJ 10MG/1ML                          8353
SODIUM CHLORIDE (SALINE) MINI BAG INF 0.9% 100ML   7415
OPTALGIN INJ 1000MG/2ML                            6692
ROCURONIUM TEVA INJ 50MG/5ML                       6369
Ready to use Solution                              6247
ATROPINE SULPHATE INJ 1MG                          5824
NEOSTIGMIN 29/M INJ 2.5MG/1ML 1ML                  5540
SUXAMETHONIUM CHLORIDE INJ BP 100MG/2ML            5270

  Column: אופן מתן  |  Unique categories: 21

                         count
אופן מתן
IV                      284325
I.V                      30441
IT                        1880
peripheral nerve block    1078
INH                        885
EP                         487
EPIDUR                     300
Epidural                   208
PR                          85
IM                          72
SC                          47
PO                          47
INF                         39
Periphe. Nerve Block        36
SL                          10
TOP                          4
IVCL                         2
S.C                          1
IL                           1
IntraARTerial                1

--- Sample Rows (first 3) ---

   Patient       מספר מקרה                    תרופה אופן מתן
0   100020 11,529,175.0000     ESMERON INJ 50MG/5ML       IV
1   100020 11,529,175.0000  TRACRIUM INJ 50 mg /5mL       IV
2   100020 11,529,175.0000  FENTANYL INJ 0.1 mg/2mL      I.V

==========================================================================================
DATASET: תרופות קבועות
File: תרופות קבועות.xlsx  |  Rows: 7,319  |  Cols: 3  |  Memory: 0.68 MB
Description: Chronic/home medications (patient-level)
==========================================================================================

--- Schema Summary ---

       column           dtype  non_null_count  null_count  null_pct  n_unique  uniqueness_ratio
0   Drug_Name          object            7319           0    0.0000      1016            0.1388
1  Entry_Date  datetime64[ns]            7319           0    0.0000      7244            0.9898
2     Patient           int64            7319           0    0.0000      1040            0.1421

--- Potential Identifier Columns ---

    column  n_unique  uniqueness_ratio  null_count       reasons  pk_candidate
0  Patient      1040            0.1421           0  name_pattern         False

--- Data Quality ---
Duplicate rows (full row): 0
No PK-candidate columns to check for duplicates.

--- Date Column Analysis ---

       column                min_date                max_date  n_unique_dates  null_count  parseable_pct
0  Entry_Date 2018-01-21 17:01:15.840 2024-12-09 22:32:04.177            1149           0       100.0000

--- Numeric Column Statistics ---

    column      count         mean          std      min       median          max
0  Patient 7,319.0000 171,023.6935 148,576.1264 802.0000 122,364.0000 673,445.0000

--- Categorical Column Analysis (Top 20) ---

  Column: Drug_Name  |  Unique categories: 1,016
  Note: High cardinality (1016 categories) — showing top 20 only

                              count
Drug_Name
CARDILOC TAB 2.5MG              221
FUSID TAB 40MG                  165
GLUCOMIN CAPLET 850MG           157
NEXIUM TAB 40MG                 110
MICROPIRIN TAB 100MG            102
OMEPRADEX CAPLET 20MG            97
VASODIP TAB 10MG                 94
CARTIA TAB 100MG                 94
ASPIRIN BAYER TAB 100MG          87
BONDORMIN TAB 0.25MG             83
NEXIUM TAB 20MG                  73
CARDILOC TAB 5MG                 73
PLAVIX TAB 75MG                  71
TRITACE TAB 2.5MG                71
TRITACE TAB 5MG                  66
METFORMIN-TEVA 5X6 TAB 850MG     61
LORIVAN TAB 1MG                  56
LIPITOR TAB 40MG                 56
CIPRALEX TAB 10MG                54
ELIQUIS 5 MG                     54

--- Sample Rows (first 3) ---

   Patient        Drug_Name              Entry_Date
0      802  PROLOL TAB 40MG 2021-05-11 11:55:14.973
1      802  NEXIUM TAB 40MG 2021-05-11 11:59:04.403
2      802  LORIVAN TAB 1MG 2021-05-11 11:56:31.913

## 5. Global Inventory Report

In [55]:
inventory_rows = []
for name, info in datasets.items():
    inventory_rows.append({
        "dataset": name,
        "file": info["file"],
        "row_count": info["n_rows"],
        "column_count": info["n_cols"],
        "memory_mb": info["memory_mb"],
        "candidate_primary_keys": ", ".join(info["pk_candidates"]) or "—",
        "case_id_column": info["keys"]["case_id"] or "—",
        "patient_id_column": info["keys"]["patient_id"] or "—",
        "medical_record_column": info["keys"]["medical_record"] or "—",
        "duplicate_rows": info["quality"]["duplicate_rows"],
        "description": info["description"],
    })

global_inventory = pd.DataFrame(inventory_rows).sort_values("row_count", ascending=False).reset_index(drop=True)

print("GLOBAL INVENTORY")
display(global_inventory)

GLOBAL INVENTORY

,dataset,file,row_count,column_count,memory_mb,candidate_primary_keys,case_id_column,patient_id_column,medical_record_column,duplicate_rows,description
0,בדיקות מעבדה,בדיקות מעבדה.csv,3715761,6,"1,415.5800",—,מספר מקרה,Patient,—,0,Pre-operative laboratory test results (long fo...
1,תרופות בניתוח,תרופות בניתוח.xlsx,319950,4,51.2900,—,מספר מקרה,Patient,—,0,Medications administered during surgery (long ...
2,ניתוחים_260415,ניתוחים_260415.xlsx,46909,44,107.9400,—,מספר מקרה,patient,Medical Record,0,"Surgery cases — procedures, timestamps, staff,..."
3,לחץ דם,לחץ דם.xlsx,35678,5,1.4300,—,מקרה,Patient,—,2864,Pre-operative blood pressure (systolic/diastol...
4,מחלות רקע,מחלות רקע.xlsx,35359,3,4.8100,—,—,Patient,—,0,"Patient background diseases (ICD-9 codes, pati..."
5,סוג דם גובה משקל BMI,סוג דם גובה משקל BMI.xlsx,34521,7,3.2200,—,מספר מקרה,Patient,—,0,"Patient vitals: blood type, height, weight, BM..."
6,הרדמה,הרדמה.xlsx,33027,3,2.6600,—,מספר מקרה,Patient,—,0,Anesthesia type per surgery case
7,צוות סיעודי בניתוח,צוות סיעודי בניתוח.xlsx,32831,3,4.8600,—,מספר מקרה,Patient,—,0,Scrub nurse assignments per case (may be multi...
8,עישון,עישון.xlsx,31661,4,1.0100,—,מספר מקרה,Patient,—,0,Smoking status per surgery case
9,זמן חתימת מנתח על sign in,זמן חתימת מנתח על sign in.xlsx,28987,3,0.7000,מספר מקרה,מספר מקרה,Patient,—,0,Surgeon electronic sign-in timestamp per case
10,זמן חתימת מנתח על sign out,זמן חתימת מנתח על sign out.xlsx,27709,3,0.6700,מספר מקרה,מספר מקרה,Patient,—,0,Surgeon electronic sign-out timestamp per case
11,סטורציה,סטורציה.xlsx,27625,4,0.8800,מקרה,מקרה,Patient,—,0,Pre-operative oxygen saturation per case
12,רגישות לתרופות,רגישות לתרופות.xlsx,8820,3,0.7800,—,—,Patient,—,0,Drug allergies/sensitivities (patient-level)
13,תרופות קבועות,תרופות קבועות.xlsx,7319,3,0.6800,—,—,Patient,—,0,Chronic/home medications (patient-level)
14,רגישות אחרת,רגישות אחרת.xlsx,1782,4,0.3000,—,—,Patient,—,0,Other allergies/sensitivities (patient-level)

## 5.1 Date Range Overview

First and last observed dates per dataset — to understand the temporal coverage (year span) across all raw data.

In [56]:
date_range_summary = build_date_range_summary(datasets)

print("DATE RANGE BY DATASET & COLUMN")
display(
    date_range_summary.assign(
        first_date=lambda d: d["first_date"].dt.strftime("%Y-%m-%d %H:%M"),
        last_date=lambda d: d["last_date"].dt.strftime("%Y-%m-%d %H:%M"),
    )
)

valid_dates = date_range_summary.dropna(subset=["first_date", "last_date"])
if valid_dates.empty:
    print("\nNo parseable date columns found across loaded datasets.")
else:
    global_first = valid_dates["first_date"].min()
    global_last = valid_dates["last_date"].max()
    global_year_span = global_last.year - global_first.year + 1

    print("\n" + "=" * 70)
    print("GLOBAL TEMPORAL COVERAGE (all datasets)")
    print("=" * 70)
    print(f"  First observed date : {global_first:%Y-%m-%d %H:%M}")
    print(f"  Last observed date  : {global_last:%Y-%m-%d %H:%M}")
    print(f"  Year span           : {global_first.year} – {global_last.year} ({global_year_span} years)")

    central = datasets.get(CENTRAL_TABLE_CANDIDATE)
    if central is not None and not central["date_analysis"].empty:
        surgery_dates = central["date_analysis"]
        primary_col = "תאריך ניתוח" if "תאריך ניתוח" in surgery_dates["column"].values else surgery_dates.iloc[0]["column"]
        surgery_row = surgery_dates.loc[surgery_dates["column"] == primary_col].iloc[0]
        s_first, s_last = surgery_row["min_date"], surgery_row["max_date"]
        print("\n" + "-" * 70)
        print(f"CENTRAL TABLE ({CENTRAL_TABLE_CANDIDATE}) — column: {primary_col}")
        print("-" * 70)
        print(f"  First surgery date  : {s_first:%Y-%m-%d %H:%M}")
        print(f"  Last surgery date   : {s_last:%Y-%m-%d %H:%M}")
        print(f"  Year span           : {s_first.year} – {s_last.year} ({s_last.year - s_first.year + 1} years)")
        print(f"  Unique surgery days : {surgery_row['n_unique_dates']:,}")

DATE RANGE BY DATASET & COLUMN

                       dataset             date_column        first_date         last_date  year_span  n_unique_dates
0                 בדיקות מעבדה             תאריך בדיקה  2019-01-04 08:55  2026-12-02 18:32     8.0000            1002
1                        הרדמה                       —               NaN               NaN        NaN               0
2    זמן חתימת מנתח על sign in             זמן sign in  2021-01-21 10:45  2026-02-18 11:40     6.0000            1819
3   זמן חתימת מנתח על sign out            זמן sign out  2021-01-21 10:24  2026-02-18 13:57     6.0000            1819
4                       לחץ דם             תאריך ניתוח  2020-01-20 00:00  2026-02-18 00:00     7.0000            2184
5                    מחלות רקע                    ICD9  1970-01-01 00:00  2054-07-21 00:00    85.0000              39
6               ניתוחים_260415             תאריך ניתוח  2020-01-20 00:00  2026-02-18 00:00     7.0000            2184
7               ניתוחים_260415               קוד אבחנה  1970-01-01 00:00  2065-06-25 00:00    96.0000              31
8               ניתוחים_260415  תאריך כניסה לחדר ניתוח  2020-01-20 00:00  2026-02-18 00:00     7.0000            2184
9               ניתוחים_260415    שעת כניסה לחדר ניתוח               NaN               NaN        NaN               0
10              ניתוחים_260415       תאריך תחילת ניתוח  2020-01-20 00:00  2026-02-18 00:00     7.0000            2184
11              ניתוחים_260415         שעת תחילת ניתוח               NaN               NaN        NaN               0
12              ניתוחים_260415       תאריך תחילת הרדמה  2020-01-20 00:00  2026-02-18 00:00     7.0000            2184
13              ניתוחים_260415         שעת תחילת הרדמה               NaN               NaN        NaN               0
14              ניתוחים_260415        תאריך סיום הרדמה  2020-01-20 00:00  2026-02-18 00:00     7.0000            2183
15              ניתוחים_260415          שעת סיום הרדמה               NaN               NaN        NaN               0
16              ניתוחים_260415        תאריך סיום ניתוח  2020-01-20 00:00  2026-02-18 00:00     7.0000            2183
17              ניתוחים_260415          שעת סיום ניתוח               NaN               NaN        NaN               0
18              ניתוחים_260415  תאריך יציאה מחדר ניתוח  2020-07-20 00:00  2026-02-18 00:00     7.0000            2000
19              ניתוחים_260415    שעת יציאה מחדר ניתוח               NaN               NaN        NaN               0
20              ניתוחים_260415    תאריך שחרור מח ניתוח  2020-01-20 00:00  2026-02-18 00:00     7.0000            2183
21              ניתוחים_260415      שעת שחרור מח ניתוח               NaN               NaN        NaN               0
22        סוג דם גובה משקל BMI             תאריך ניתוח  2020-01-20 00:00  2026-02-18 00:00     7.0000            2184
23                     סטורציה             תאריך ניתוח  2020-01-20 00:00  2026-02-18 00:00     7.0000            2182
24                       עישון              מועד ניתוח  2020-01-20 07:38  2026-02-18 11:33     7.0000            2184
25          צוות סיעודי בניתוח                       —               NaN               NaN        NaN               0
26                 רגישות אחרת              מועד כתיבה  2018-01-30 21:21  2026-02-18 08:51     9.0000            1059
27              רגישות לתרופות              Entry_Date  2018-01-13 01:42  2026-02-17 09:56     9.0000            2140
28               תרופות בניתוח                       —               NaN               NaN        NaN               0
29               תרופות קבועות              Entry_Date  2018-01-21 17:01  2024-12-09 22:32     7.0000            1149

======================================================================
GLOBAL TEMPORAL COVERAGE (all datasets)
======================================================================
  First observed date : 1970-01-01 00:00
  Last observed date  : 2065-06-25 00:00
  Year span           : 1970 – 2065 (96 years)

----------------------------------------------------------------------
CENTRAL TABLE (ניתוחים_260415) — column: תאריך ניתוח
----------------------------------------------------------------------
  First surgery date  : 2020-01-20 00:00
  Last surgery date   : 2026-02-18 00:00
  Year span           : 2020 – 2026 (7 years)
  Unique surgery days : 2,184

## 5.2 Department Breakdown — Unique Values per מחלקה

The surgery dataset mixes three hospital departments: **אף אוזן גרון**, **אורטופדיה**, and **כירורגיה** (stored as sub-units in `מחלקה מנתחת`, e.g. "אורטופדיה א").

Below: volume per sub-unit and count of distinct values in key clinical columns within each parent department.

In [57]:
central = datasets.get(CENTRAL_TABLE_CANDIDATE)
if central is None or SURGERY_DEPT_COLUMN not in central["df"].columns:
    print(f"Department column '{SURGERY_DEPT_COLUMN}' not found in {CENTRAL_TABLE_CANDIDATE}.")
else:
    surgery_df = central["df"]

    print("SURGERY VOLUME BY SUB-UNIT & PARENT DEPARTMENT")
    dept_volume = department_volume_summary(surgery_df)
    display(dept_volume)

    parent_totals = (
        dept_volume.groupby("מחלקה ראשית", dropna=False)[["n_rows", "n_unique_cases", "n_unique_patients"]]
        .sum()
        .reindex(PARENT_DEPARTMENTS)
        .reset_index()
    )
    print("\nTOTALS BY PARENT DEPARTMENT (אף אוזן גרון | אורטופדיה | כירורגיה)")
    display(parent_totals)

    print("\nUNIQUE VALUES PER COLUMN — BY PARENT DEPARTMENT")
    dept_unique = unique_values_by_department(surgery_df)
    display(dept_unique)

    print("\nColumn legend:")
    for col in dept_unique["column"]:
        print(f"  • {col}")

SURGERY VOLUME BY SUB-UNIT & PARENT DEPARTMENT

    מחלקה מנתחת   מחלקה ראשית  n_rows  n_unique_cases  n_unique_patients
0  אורטופדיה א      אורטופדיה    9157            7123               6374
1   אורטופדיה ב     אורטופדיה    9906            7258               6185
2  אף אוזן גרון  אף אוזן גרון    8953            5309               4784
3    כירורגיה א      כירורגיה    9977            7484               6885
4    כירורגיה ב      כירורגיה    8916            6431               5952

TOTALS BY PARENT DEPARTMENT (אף אוזן גרון | אורטופדיה | כירורגיה)

    מחלקה ראשית  n_rows  n_unique_cases  n_unique_patients
0  אף אוזן גרון    8953            5309               4784
1     אורטופדיה   19063           14381              12559
2      כירורגיה   18893           13915              12837

UNIQUE VALUES PER COLUMN — BY PARENT DEPARTMENT

מחלקה ראשית        column  אף אוזן גרון  אורטופדיה  כירורגיה
0                   מרדים           657       1250      1176
1             הרדמה פירוט            17        125        42
2                     חדר            11         10        11
3                     מין             2          2         2
4              מנתח אחראי           121        201       256
5               סוג הרדמה            10         15        14
6                סוג מקרה             2          2         2
7               סוג ניתוח             8         11         8
8             צד פרוצדורה             3          3         3
9               קוד אבחנה           499       1026      1033
10           קוד פרוצדורה           475        919      1116
11               שם אבחנה           681       1236      1285
12            שם פרוצדורה           539       1191      1331

Column legend:
  •  מרדים
  • הרדמה פירוט
  • חדר
  • מין
  • מנתח אחראי
  • סוג הרדמה
  • סוג מקרה
  • סוג ניתוח
  • צד פרוצדורה
  • קוד אבחנה
  • קוד פרוצדורה
  • שם אבחנה
  • שם פרוצדורה

## 6. Cross-Table Analysis

Identify shared columns, overlapping key values, and suggested relationships.

In [58]:
# 6.1 Columns appearing in multiple datasets
column_occurrence = defaultdict(list)
for name, info in datasets.items():
    for col in info["df"].columns:
        column_occurrence[str(col)].append(name)

shared_columns = {
    col: tables for col, tables in column_occurrence.items() if len(tables) > 1
}

shared_cols_df = pd.DataFrame([
    {"column": col, "n_datasets": len(tables), "datasets": ", ".join(sorted(tables))}
    for col, tables in sorted(shared_columns.items(), key=lambda x: -len(x[1]))
])

print("Columns appearing in multiple datasets:")
display(shared_cols_df)

Columns appearing in multiple datasets:

        column  n_datasets                                           datasets
0      Patient          14  בדיקות מעבדה, הרדמה, זמן חתימת מנתח על sign in...
1    מספר מקרה           9  בדיקות מעבדה, הרדמה, זמן חתימת מנתח על sign in...
2  תאריך ניתוח           4  לחץ דם, ניתוחים_260415, סוג דם גובה משקל BMI, ...
3         מקרה           2                                    לחץ דם, סטורציה
4    Drug_Name           2                      רגישות לתרופות, תרופות קבועות
5   Entry_Date           2                      רגישות לתרופות, תרופות קבועות

In [59]:
# 6.2 Semantic key registry for relationship analysis
key_registry = {}
for name, info in datasets.items():
    key_registry[name] = {
        "case_id": info["keys"]["case_id"],
        "patient_id": info["keys"]["patient_id"],
        "medical_record": info["keys"]["medical_record"],
    }

key_registry_df = pd.DataFrame(key_registry).T
print("Standardized key column mapping per dataset:")
display(key_registry_df)

Standardized key column mapping per dataset:

                              case_id patient_id  medical_record
בדיקות מעבדה                מספר מקרה    Patient            None
הרדמה                       מספר מקרה    Patient            None
זמן חתימת מנתח על sign in   מספר מקרה    Patient            None
זמן חתימת מנתח על sign out  מספר מקרה    Patient            None
לחץ דם                           מקרה    Patient            None
מחלות רקע                        None    Patient            None
ניתוחים_260415              מספר מקרה    patient  Medical Record
סוג דם גובה משקל BMI        מספר מקרה    Patient            None
סטורציה                          מקרה    Patient            None
עישון                       מספר מקרה    Patient            None
צוות סיעודי בניתוח          מספר מקרה    Patient            None
רגישות אחרת                      None    Patient            None
רגישות לתרופות                   None    Patient            None
תרופות בניתוח               מספר מקרה    Patient            None
תרופות קבועות                    None    Patient            None

In [60]:
# 6.3 Pairwise relationship detection on shared / aliased key columns

def get_column_series(df, col):
    s = df[col].dropna()
    if pd.api.types.is_numeric_dtype(s):
        return s.astype("Int64").astype(str)
    return s.astype(str).str.strip()


def compute_pairwise_relationships(datasets: dict) -> pd.DataFrame:
    relationships = []

    # Build list of (dataset, semantic_role, column_name)
    key_columns = []
    for ds_name, info in datasets.items():
        for role, col in info["keys"].items():
            if col:
                key_columns.append((ds_name, role, col))

    # Also compare columns with identical names across tables
    for col_name, ds_list in shared_columns.items():
        for ds_a, ds_b in combinations(sorted(ds_list), 2):
            key_columns.append((ds_a, f"shared:{col_name}", col_name))
            key_columns.append((ds_b, f"shared:{col_name}", col_name))

    # Deduplicate pairs
    seen_pairs = set()
    for i, (ds_a, role_a, col_a) in enumerate(key_columns):
        for ds_b, role_b, col_b in key_columns[i + 1:]:
            if ds_a == ds_b:
                continue
            pair_key = tuple(sorted([(ds_a, col_a), (ds_b, col_b)]))
            if pair_key in seen_pairs:
                continue
            seen_pairs.add(pair_key)

            df_a = datasets[ds_a]["df"]
            df_b = datasets[ds_b]["df"]
            if col_a not in df_a.columns or col_b not in df_b.columns:
                continue

            s_a = get_column_series(df_a, col_a)
            s_b = get_column_series(df_b, col_b)
            set_a = set(s_a.unique())
            set_b = set(s_b.unique())
            overlap = set_a & set_b

            if not overlap:
                continue

            n_a, u_a = len(s_a), len(set_a)
            n_b, u_b = len(s_b), len(set_b)
            rel_type = classify_relationship(n_a, u_a, n_b, u_b, len(overlap))

            # Suggest relationship label
            if "case_id" in role_a or "case_id" in role_b or "מקרה" in col_a or "מקרה" in col_b:
                suggested = "Surgery case linkage"
            elif "patient_id" in role_a or "patient_id" in role_b:
                suggested = "Patient linkage"
            elif "medical_record" in role_a or "medical_record" in role_b:
                suggested = "Medical record linkage"
            else:
                suggested = "Shared attribute"

            relationships.append({
                "table_a": ds_a,
                "column_a": col_a,
                "table_b": ds_b,
                "column_b": col_b,
                "overlap_count": len(overlap),
                "overlap_pct_a": round(100 * len(overlap) / max(u_a, 1), 2),
                "overlap_pct_b": round(100 * len(overlap) / max(u_b, 1), 2),
                "rows_a": n_a,
                "unique_a": u_a,
                "rows_b": n_b,
                "unique_b": u_b,
                "relationship_type": rel_type,
                "suggested_relationship": suggested,
            })

    rel_df = pd.DataFrame(relationships)
    if rel_df.empty:
        return rel_df
    return rel_df.sort_values(["suggested_relationship", "overlap_count"], ascending=[True, False]).reset_index(drop=True)


relationship_report = compute_pairwise_relationships(datasets)

print("RELATIONSHIP REPORT")
print("=" * 90)
if relationship_report.empty:
    print("No overlapping key relationships detected.")
else:
    display(relationship_report[[
        "table_a", "column_a", "table_b", "column_b",
        "suggested_relationship", "relationship_type",
        "overlap_count", "overlap_pct_a", "overlap_pct_b",
    ]])

RELATIONSHIP REPORT
==========================================================================================

                  table_a   column_a                     table_b   column_b suggested_relationship   relationship_type  overlap_count  overlap_pct_a  overlap_pct_b
0          ניתוחים_260415    patient        סוג דם גובה משקל BMI    Patient        Patient linkage  Many-to-Many (N:N)          28461       100.0000       100.0000
1                   הרדמה    Patient              ניתוחים_260415    patient        Patient linkage  Many-to-Many (N:N)          27845       100.0000        97.8400
2                   הרדמה    Patient        סוג דם גובה משקל BMI    Patient        Patient linkage  Many-to-Many (N:N)          27845       100.0000        97.8400
3          ניתוחים_260415    patient               תרופות בניתוח    Patient        Patient linkage  Many-to-Many (N:N)          27185        95.5200       100.0000
4    סוג דם גובה משקל BMI    Patient               תרופות בניתוח    Patient        Patient linkage  Many-to-Many (N:N)          27185        95.5200       100.0000
..                    ...        ...                         ...        ...                    ...                 ...            ...            ...            ...
176          בדיקות מעבדה  מספר מקרה                       עישון  מספר מקרה   Surgery case linkage  Many-to-Many (N:N)          17794        91.7200        60.0000
177          בדיקות מעבדה  מספר מקרה          צוות סיעודי בניתוח  מספר מקרה   Surgery case linkage  Many-to-Many (N:N)          17762        91.5600        58.2800
178          בדיקות מעבדה  מספר מקרה                     סטורציה       מקרה   Surgery case linkage  Many-to-Many (N:N)          16460        84.8500        61.8400
179          בדיקות מעבדה  מספר מקרה   זמן חתימת מנתח על sign in  מספר מקרה   Surgery case linkage  Many-to-Many (N:N)          15779        81.3400        57.0100
180          בדיקות מעבדה  מספר מקרה  זמן חתימת מנתח על sign out  מספר מקרה   Surgery case linkage  Many-to-Many (N:N)          15235        78.5300        57.5000

[181 rows x 9 columns]

In [61]:
# 6.4 Case-level granularity check (critical for merge planning)
case_granularity = []
for name, info in datasets.items():
    case_col = info["keys"]["case_id"]
    if case_col:
        df = info["df"]
        n_rows = len(df)
        n_cases = df[case_col].nunique(dropna=True)
        rows_per_case = round(n_rows / max(n_cases, 1), 2)
        case_granularity.append({
            "dataset": name,
            "case_id_column": case_col,
            "n_rows": n_rows,
            "n_unique_cases": n_cases,
            "avg_rows_per_case": rows_per_case,
            "granularity": "1 row/case" if rows_per_case == 1 else f"~{rows_per_case} rows/case (multi-record)",
        })

case_granularity_df = pd.DataFrame(case_granularity).sort_values("avg_rows_per_case", ascending=False)
print("Case-level granularity (important for join duplication risk):")
display(case_granularity_df)

Case-level granularity (important for join duplication risk):

                       dataset case_id_column   n_rows  n_unique_cases  avg_rows_per_case                       granularity
0                 בדיקות מעבדה      מספר מקרה  3715761           19400           191.5300  ~191.53 rows/case (multi-record)
10               תרופות בניתוח      מספר מקרה   319950           31791            10.0600   ~10.06 rows/case (multi-record)
5               ניתוחים_260415      מספר מקרה    46909           33500             1.4000     ~1.4 rows/case (multi-record)
4                       לחץ דם           מקרה    35678           31816             1.1200    ~1.12 rows/case (multi-record)
9           צוות סיעודי בניתוח      מספר מקרה    32831           30476             1.0800    ~1.08 rows/case (multi-record)
8                        עישון      מספר מקרה    31661           29659             1.0700    ~1.07 rows/case (multi-record)
2    זמן חתימת מנתח על sign in      מספר מקרה    28987           27677             1.0500    ~1.05 rows/case (multi-record)
3   זמן חתימת מנתח על sign out      מספר מקרה    27709           26494             1.0500    ~1.05 rows/case (multi-record)
7                      סטורציה           מקרה    27625           26615             1.0400    ~1.04 rows/case (multi-record)
6         סוג דם גובה משקל BMI      מספר מקרה    34521           33500             1.0300    ~1.03 rows/case (multi-record)
1                        הרדמה      מספר מקרה    33027           32681             1.0100    ~1.01 rows/case (multi-record)

In [62]:
# 6.5 Patient-level tables without case ID (require careful join path)
patient_only_tables = []
for name, info in datasets.items():
    if info["keys"]["patient_id"] and not info["keys"]["case_id"]:
        df = info["df"]
        patient_col = info["keys"]["patient_id"]
        patient_only_tables.append({
            "dataset": name,
            "patient_id_column": patient_col,
            "n_rows": len(df),
            "n_unique_patients": df[patient_col].nunique(dropna=True),
            "avg_records_per_patient": round(len(df) / max(df[patient_col].nunique(), 1), 2),
            "join_risk": "Patient-level only — joining directly to surgeries may duplicate or require aggregation",
        })

if patient_only_tables:
    print("Patient-level tables (no case ID):")
    display(pd.DataFrame(patient_only_tables))
else:
    print("All tables have case-level keys.")

Patient-level tables (no case ID):

          dataset patient_id_column  n_rows  n_unique_patients  avg_records_per_patient                                          join_risk
0       מחלות רקע           Patient   35359              10781                   3.2800  Patient-level only — joining directly to surge...
1     רגישות אחרת           Patient    1782               1395                   1.2800  Patient-level only — joining directly to surge...
2  רגישות לתרופות           Patient    8820               5196                   1.7000  Patient-level only — joining directly to surge...
3   תרופות קבועות           Patient    7319               1040                   7.0400  Patient-level only — joining directly to surge...

## 7. Merge Planning Report

Based on schema discovery — **no merges performed in this notebook**.

In [63]:
# Identify likely central table
central = datasets.get(CENTRAL_TABLE_CANDIDATE)
if central:
    print("LIKELY CENTRAL TABLE:", CENTRAL_TABLE_CANDIDATE)
    print("-" * 60)
    print(f"Rows: {central['n_rows']:,}")
    print(f"Unique cases (מספר מקרה): {central['df']['מספר מקרה'].nunique():,}")
    print(f"Unique patients: {central['df']['patient'].nunique():,}")
    print(f"Columns: {central['n_cols']}")
    print()
    print("Why this should be the central table:")
    print("  1. Contains the prediction target inputs: surgery start/end timestamps")
    print("  2. Rich case-level context: procedure, diagnosis, department, staff, anesthesia")
    print("  3. Has both case ID (מספר מקרה) and patient ID (patient) for downstream joins")
    print("  4. Largest integrated clinical record per surgery event")
else:
    print(f"Central table candidate '{CENTRAL_TABLE_CANDIDATE}' not found.")

LIKELY CENTRAL TABLE: ניתוחים_260415
------------------------------------------------------------
Rows: 46,909
Unique cases (מספר מקרה): 33,500
Unique patients: 28,461
Columns: 44

Why this should be the central table:
  1. Contains the prediction target inputs: surgery start/end timestamps
  2. Rich case-level context: procedure, diagnosis, department, staff, anesthesia
  3. Has both case ID (מספר מקרה) and patient ID (patient) for downstream joins
  4. Largest integrated clinical record per surgery event

In [64]:
# Proposed merge order and strategy
merge_strategy = pd.DataFrame([
    {"order": 1, "table": "ניתוחים_260415", "join_key": "מספר מקרה", "join_type": "BASE TABLE", "notes": "Surgery fact table — one row per procedure; deduplicate or aggregate for case-level target"},
    {"order": 2, "table": "הרדמה", "join_key": "מספר מקרה", "join_type": "LEFT JOIN", "notes": "1:1 case attribute — low duplication risk"},
    {"order": 3, "table": "זמן חתימת מנתח על sign in", "join_key": "מספר מקרה", "join_type": "LEFT JOIN", "notes": "Surgeon sign-in timestamp"},
    {"order": 4, "table": "זמן חתימת מנתח על sign out", "join_key": "מספר מקרה", "join_type": "LEFT JOIN", "notes": "Surgeon sign-out timestamp"},
    {"order": 5, "table": "סוג דם גובה משקל BMI", "join_key": "מספר מקרה", "join_type": "LEFT JOIN", "notes": "Pre-op vitals and blood type"},
    {"order": 6, "table": "לחץ דם", "join_key": "מקרה → מספר מקרה", "join_type": "LEFT JOIN", "notes": "Rename מקרה to מספר מקרה before join"},
    {"order": 7, "table": "סטורציה", "join_key": "מקרה → מספר מקרה", "join_type": "LEFT JOIN", "notes": "Rename מקרה to מספר מקרה before join"},
    {"order": 8, "table": "עישון", "join_key": "מספר מקרה", "join_type": "LEFT JOIN", "notes": "Smoking status per case"},
    {"order": 9, "table": "צוות סיעודי בניתוח", "join_key": "מספר מקרה", "join_type": "LEFT JOIN + AGGREGATE", "notes": "Multiple nurses per case — pivot/aggregate to avoid row explosion"},
    {"order": 10, "table": "תרופות בניתוח", "join_key": "מספר מקרה", "join_type": "LEFT JOIN + AGGREGATE", "notes": "319K rows — long format; aggregate or feature-engineer before join"},
    {"order": 11, "table": "בדיקות מעבדה", "join_key": "מספר מקרה", "join_type": "LEFT JOIN + AGGREGATE", "notes": "3.7M rows — pivot lab tests or filter pre-op window; high cardinality"},
    {"order": 12, "table": "מחלות רקע", "join_key": "Patient → patient", "join_type": "LEFT JOIN + AGGREGATE", "notes": "Patient-level ICD codes — aggregate to case via patient ID"},
    {"order": 13, "table": "רגישות לתרופות", "join_key": "Patient → patient", "join_type": "LEFT JOIN + AGGREGATE", "notes": "Patient-level drug allergies"},
    {"order": 14, "table": "רגישות אחרת", "join_key": "Patient → patient", "join_type": "LEFT JOIN + AGGREGATE", "notes": "Patient-level other allergies"},
    {"order": 15, "table": "תרופות קבועות", "join_key": "Patient → patient", "join_type": "LEFT JOIN + AGGREGATE", "notes": "Chronic medications — aggregate before join"},
])

print("RECOMMENDED MERGE ORDER (future ETL)")
display(merge_strategy)

RECOMMENDED MERGE ORDER (future ETL)

    order                       table           join_key              join_type                                              notes
0       1              ניתוחים_260415          מספר מקרה             BASE TABLE  Surgery fact table — one row per procedure; de...
1       2                       הרדמה          מספר מקרה              LEFT JOIN          1:1 case attribute — low duplication risk
2       3   זמן חתימת מנתח על sign in          מספר מקרה              LEFT JOIN                          Surgeon sign-in timestamp
3       4  זמן חתימת מנתח על sign out          מספר מקרה              LEFT JOIN                         Surgeon sign-out timestamp
4       5        סוג דם גובה משקל BMI          מספר מקרה              LEFT JOIN                       Pre-op vitals and blood type
5       6                      לחץ דם   מקרה → מספר מקרה              LEFT JOIN               Rename מקרה to מספר מקרה before join
6       7                     סטורציה   מקרה → מספר מקרה              LEFT JOIN               Rename מקרה to מספר מקרה before join
7       8                       עישון          מספר מקרה              LEFT JOIN                            Smoking status per case
8       9          צוות סיעודי בניתוח          מספר מקרה  LEFT JOIN + AGGREGATE  Multiple nurses per case — pivot/aggregate to ...
9      10               תרופות בניתוח          מספר מקרה  LEFT JOIN + AGGREGATE  319K rows — long format; aggregate or feature-...
10     11                בדיקות מעבדה          מספר מקרה  LEFT JOIN + AGGREGATE  3.7M rows — pivot lab tests or filter pre-op w...
11     12                   מחלות רקע  Patient → patient  LEFT JOIN + AGGREGATE  Patient-level ICD codes — aggregate to case vi...
12     13              רגישות לתרופות  Patient → patient  LEFT JOIN + AGGREGATE                       Patient-level drug allergies
13     14                 רגישות אחרת  Patient → patient  LEFT JOIN + AGGREGATE                      Patient-level other allergies
14     15               תרופות קבועות  Patient → patient  LEFT JOIN + AGGREGATE        Chronic medications — aggregate before join

In [65]:
# Merge risk register
merge_risks = pd.DataFrame([
    {
        "risk": "Row duplication from multi-record tables",
        "affected_tables": "ניתוחים_260415 (multi-procedure), צוות סיעודי, תרופות בניתוח, בדיקות מעבדה",
        "severity": "HIGH",
        "mitigation": "Aggregate to case level before joining; define grain (case vs procedure) explicitly",
    },
    {
        "risk": "Inconsistent case ID column naming",
        "affected_tables": "לחץ דם, סטורציה (מקרה) vs others (מספר מקרה)",
        "severity": "MEDIUM",
        "mitigation": "Standardize column names in ETL staging layer",
    },
    {
        "risk": "Patient-level tables joined on case grain",
        "affected_tables": "מחלות רקע, רגישות לתרופות, רגישות אחרת, תרופות קבועות",
        "severity": "HIGH",
        "mitigation": "Join via patient ID, aggregate chronic conditions/allergies; watch for many-to-many explosion",
    },
    {
        "risk": "Missing / mismatched keys",
        "affected_tables": "All satellite tables",
        "severity": "MEDIUM",
        "mitigation": "Left joins + null rate monitoring; investigate cases in surgeries not in satellites",
    },
    {
        "risk": "Headerless lab CSV",
        "affected_tables": "בדיקות מעבדה",
        "severity": "LOW",
        "mitigation": "Assign column names at load time (done in this notebook)",
    },
    {
        "risk": "Large table memory / performance",
        "affected_tables": "בדיקות מעבדה (3.7M rows), תרופות בניתוח (320K rows)",
        "severity": "MEDIUM",
        "mitigation": "Filter to relevant cases and pre-op window; aggregate before merge",
    },
    {
        "risk": "Ambiguous join for patient ID",
        "affected_tables": "Patient vs Medical Record vs patient columns",
        "severity": "MEDIUM",
        "mitigation": "Validate Patient ID mapping between tables; Medical Record may differ from Patient",
    },
    {
        "risk": "Cartesian product from unaggregated long-format tables",
        "affected_tables": "בדיקות מעבדה × תרופות בניתוח if joined without aggregation",
        "severity": "CRITICAL",
        "mitigation": "Never join two long-format tables directly — aggregate each to case level first",
    },
])

print("MERGE RISK REGISTER")
display(merge_risks)

MERGE RISK REGISTER

                                                risk                                    affected_tables  severity                                         mitigation
0           Row duplication from multi-record tables  ניתוחים_260415 (multi-procedure), צוות סיעודי,...      HIGH  Aggregate to case level before joining; define...
1                 Inconsistent case ID column naming       לחץ דם, סטורציה (מקרה) vs others (מספר מקרה)    MEDIUM      Standardize column names in ETL staging layer
2          Patient-level tables joined on case grain  מחלות רקע, רגישות לתרופות, רגישות אחרת, תרופות...      HIGH  Join via patient ID, aggregate chronic conditi...
3                          Missing / mismatched keys                               All satellite tables    MEDIUM  Left joins + null rate monitoring; investigate...
4                                 Headerless lab CSV                                       בדיקות מעבדה       LOW  Assign column names at load time (done in this...
5                   Large table memory / performance  בדיקות מעבדה (3.7M rows), תרופות בניתוח (320K ...    MEDIUM  Filter to relevant cases and pre-op window; ag...
6                      Ambiguous join for patient ID       Patient vs Medical Record vs patient columns    MEDIUM  Validate Patient ID mapping between tables; Me...
7  Cartesian product from unaggregated long-forma...  בדיקות מעבדה × תרופות בניתוח if joined without...  CRITICAL  Never join two long-format tables directly — a...

## 8. Executive Summary

Auto-generated summary based on the inventory analysis above.

In [66]:
# Build executive summary from analysis results
exec_lines = []
exec_lines.append("=" * 80)
exec_lines.append("EXECUTIVE SUMMARY — Raw Data Inventory")
exec_lines.append("Hillel Yaffe Medical Center | Surgery Duration Prediction")
exec_lines.append("=" * 80)

exec_lines.append("\n1. DATASET OVERVIEW (what each file likely represents)")
exec_lines.append("-" * 60)
for name, info in sorted(datasets.items(), key=lambda x: x[0]):
    exec_lines.append(f"  • {name}: {info['description']} [{info['n_rows']:,} rows]")

exec_lines.append("\n2. CENTRAL TABLE RECOMMENDATION")
exec_lines.append("-" * 60)
exec_lines.append(f"  Central table: {CENTRAL_TABLE_CANDIDATE} (Surgeries)")
exec_lines.append("  Rationale: Contains surgery timestamps (target variable), procedure/diagnosis")
exec_lines.append("  codes, department, staff, and both case + patient identifiers.")

exec_lines.append("\n3. RECOMMENDED JOIN KEYS")
exec_lines.append("-" * 60)
exec_lines.append("  Primary (case-level):  מספר מקרה  (standardize מקרה → מספר מקרה in לחץ דם, סטורציה)")
exec_lines.append("  Secondary (patient-level):  Patient / patient  (for chronic conditions, allergies, home meds)")
exec_lines.append("  Avoid direct join on:  Medical Record  (verify mapping to Patient first)")

exec_lines.append("\n4. KEY RELATIONSHIPS DISCOVERED")
exec_lines.append("-" * 60)
if not relationship_report.empty:
    top_rels = relationship_report.head(10)
    for _, r in top_rels.iterrows():
        exec_lines.append(
            f"  • {r['table_a']}.{r['column_a']} ↔ {r['table_b']}.{r['column_b']}"
            f"  [{r['relationship_type']}] — {r['suggested_relationship']}"
        )
else:
    exec_lines.append("  (Run cross-table analysis cells to populate)")

exec_lines.append("\n5. MERGE RISKS")
exec_lines.append("-" * 60)
for _, r in merge_risks.iterrows():
    exec_lines.append(f"  [{r['severity']}] {r['risk']}")

exec_lines.append("\n6. RECOMMENDED NEXT STEPS FOR ETL PIPELINE")
exec_lines.append("-" * 60)
next_steps = [
    "Define modeling grain: one row per surgery case (מספר מקרה) vs per procedure",
    "Build staging layer: standardize column names (מקרה → מספר מקרה, Patient → patient)",
    "Compute target variable: surgery duration from start/end timestamps in ניתוחים",
    "Aggregate long-format tables (labs, intra-op meds, nursing) to case level",
    "Aggregate patient-level tables (ICD, allergies, chronic meds) before joining",
    "Profile key overlap rates between surgeries and each satellite table",
    "Document null rates and unmatched cases after each staged join",
    "Proceed to 02_staging / 03_feature_engineering notebooks",
]
for i, step in enumerate(next_steps, 1):
    exec_lines.append(f"  {i}. {step}")

exec_lines.append("\n" + "=" * 80)

executive_summary = "\n".join(exec_lines)
print(executive_summary)

================================================================================
EXECUTIVE SUMMARY — Raw Data Inventory
Hillel Yaffe Medical Center | Surgery Duration Prediction
================================================================================

1. DATASET OVERVIEW (what each file likely represents)
------------------------------------------------------------
  • בדיקות מעבדה: Pre-operative laboratory test results (long format, multiple tests per case) [3,715,761 rows]
  • הרדמה: Anesthesia type per surgery case [33,027 rows]
  • זמן חתימת מנתח על sign in: Surgeon electronic sign-in timestamp per case [28,987 rows]
  • זמן חתימת מנתח על sign out: Surgeon electronic sign-out timestamp per case [27,709 rows]
  • לחץ דם: Pre-operative blood pressure (systolic/diastolic) per case [35,678 rows]
  • מחלות רקע: Patient background diseases (ICD-9 codes, patient-level) [35,359 rows]
  • ניתוחים_260415: Surgery cases — procedures, timestamps, staff, anesthesia (likely central fact table) [46,909 rows]
  • סוג דם גובה משקל BMI: Patient vitals: blood type, height, weight, BMI per case [34,521 rows]
  • סטורציה: Pre-operative oxygen saturation per case [27,625 rows]
  • עישון: Smoking status per surgery case [31,661 rows]
  • צוות סיעודי בניתוח: Scrub nurse assignments per case (may be multi-valued) [32,831 rows]
  • רגישות אחרת: Other allergies/sensitivities (patient-level) [1,782 rows]
  • רגישות לתרופות: Drug allergies/sensitivities (patient-level) [8,820 rows]
  • תרופות בניתוח: Medications administered during surgery (long format) [319,950 rows]
  • תרופות קבועות: Chronic/home medications (patient-level) [7,319 rows]

2. CENTRAL TABLE RECOMMENDATION
------------------------------------------------------------
  Central table: ניתוחים_260415 (Surgeries)
  Rationale: Contains surgery timestamps (target variable), procedure/diagnosis
  codes, department, staff, and both case + patient identifiers.

3. RECOMMENDED JOIN KEYS
------------------------------------------------------------
  Primary (case-level):  מספר מקרה  (standardize מקרה → מספר מקרה in לחץ דם, סטורציה)
  Secondary (patient-level):  Patient / patient  (for chronic conditions, allergies, home meds)
  Avoid direct join on:  Medical Record  (verify mapping to Patient first)

4. KEY RELATIONSHIPS DISCOVERED
------------------------------------------------------------
  • ניתוחים_260415.patient ↔ סוג דם גובה משקל BMI.Patient  [Many-to-Many (N:N)] — Patient linkage
  • הרדמה.Patient ↔ ניתוחים_260415.patient  [Many-to-Many (N:N)] — Patient linkage
  • הרדמה.Patient ↔ סוג דם גובה משקל BMI.Patient  [Many-to-Many (N:N)] — Patient linkage
  • ניתוחים_260415.patient ↔ תרופות בניתוח.Patient  [Many-to-Many (N:N)] — Patient linkage
  • סוג דם גובה משקל BMI.Patient ↔ תרופות בניתוח.Patient  [Many-to-Many (N:N)] — Patient linkage
  • לחץ דם.Patient ↔ ניתוחים_260415.patient  [Many-to-Many (N:N)] — Patient linkage
  • לחץ דם.Patient ↔ סוג דם גובה משקל BMI.Patient  [Many-to-Many (N:N)] — Patient linkage
  • הרדמה.Patient ↔ תרופות בניתוח.Patient  [Many-to-Many (N:N)] — Patient linkage
  • הרדמה.Patient ↔ לחץ דם.Patient  [Many-to-Many (N:N)] — Patient linkage
  • ניתוחים_260415.patient ↔ צוות סיעודי בניתוח.Patient  [Many-to-Many (N:N)] — Patient linkage

5. MERGE RISKS
------------------------------------------------------------
  [HIGH] Row duplication from multi-record tables
  [MEDIUM] Inconsistent case ID column naming
  [HIGH] Patient-level tables joined on case grain
  [MEDIUM] Missing / mismatched keys
  [LOW] Headerless lab CSV
  [MEDIUM] Large table memory / performance
  [MEDIUM] Ambiguous join for patient ID
  [CRITICAL] Cartesian product from unaggregated long-format tables

6. RECOMMENDED NEXT STEPS FOR ETL PIPELINE
------------------------------------------------------------
  1. Define modeling grain: one row per surgery case (מספר מקרה) vs per procedure
  2. Build staging layer: standardize column names (מקרה → מספר מקרה, Patient → patient)
  3. Compute target variable: surgery duration from start/end timestamps in ניתוחים
  4. Aggregate long-format tables (labs, intra-op meds, nursing) to case level
  5. Aggregate patient-level tables (ICD, allergies, chronic meds) before joining
  6. Profile key overlap rates between surgeries and each satellite table
  7. Document null rates and unmatched cases after each staged join
  8. Proceed to 02_staging / 03_feature_engineering notebooks

================================================================================

---

### Notes

- This notebook is **read-only** with respect to source files under `data/raw/`.
- The lab file `בדיקות מעבדה.csv` has **no header row**; column names were assigned at load time.
- Column `מקרה` in some tables is equivalent to `מספר מקרה` in others — standardize during ETL.
- Before merging, decide whether the modeling unit is **surgery case** or **procedure** (ניתוחים has multiple procedures per case).